### ISSUE TITLE
Append to body

### ISSUE THREAD

**Issue by ArielGueta** [Simonwep/pickr#1]
Thanks for this library, looks fantastic! 

The problem is that we can't use it with elements that are with overflow hidden, there are any plans to add an option for append to the body? 

Thanks in advance.

**Comment by Simonwep** [comment]
Hey, thanks!
Not yet, but I will try to find a workaround.
Any ideas / suggestions are welcome!

**Comment by ArielGueta** [comment]
Actually, I think it will be awesome also to control the position of the color picker relative to the origin. I suggest [Popper](https://popper.js.org/) js for this task. It will be really great ability.

**Comment by Simonwep** [comment]
Yeah, but I don't really want a dependency with, on top of that, a size of about ~20kb (Minified). That would be bigger than the compressed pickr.js. What do you mean exactly with
>  I think it will be awesome also to control the position of the color picker relative to the origin.

If you mean the position relative to the button, you can use default css, the button has `position: relative`

**Comment by ArielGueta** [comment]
Yes, that's what I meant. I know, but with Popper, for example, it will give you an API to manage this and will also take care to update the position if the content doesn't fit. But I see your concern.

**Comment by Simonwep** [comment]
Okay, that's right. I will, in the next days, implement a feature which will take care about the main things like position updating if it goes out of bounds. Greate idea!

**Comment by ArielGueta** [comment]
Awesome, thanks!

**Comment by Simonwep** [comment]
Yeah, I've added it in dd7f389ff357c5be94f8d7fe8ae3cb8392136939.
I'ts currently in no release but if you want to use it you can clone / download the minified files :). (I build the [dist files](https://github.com/Simonwep/pickr/tree/master/dist) on every commit)

**Comment by ArielGueta** [comment]
Is it appended to the body, now?

**Comment by Simonwep** [comment]
Finally it's possible, added in 76d20411628af467823b7fd681880f5a66ed5806. Its part of version [`0.1.2`](https://github.com/Simonwep/pickr/releases/tag/0.1.2), see [`appendToBody`](https://github.com/Simonwep/pickr#optional-options) option.

**Comment by ArielGueta** [comment]
Wow, this is great. Thanks!!
