### ISSUE TITLE
Set limit in color code when using mousewheel

### ISSUE THREAD

**Issue by bjarnef** [Simonwep/pickr#100]
The color picker looks amazing and works really well. Thank for sharing this! 👍 

However I noticed a minor issue when using mousewheel in color code input to adjust color when trying out the demo https://simonwep.github.io/pickr/

- In HEXA mode I think the int values should be between 0 - 99
- In RGBA mode I think the values should be between 0 - 255 and for alpha between 0 and 1 (probably with a step size of 0.1).
- HSVA mode I think the percentage values should be between 0 - 100% and for alpha between 0 and 1 (probably with a step size of 0.1).

**Comment by Simonwep** [comment]
Wow, never thought someone would actually use it haha, anyway yea - afterwards it would be better to limit these. I'll take a look at it!

**Comment by Simonwep** [comment]
Added :) Thanks for the FR, proposals like this making it awesome in the first place 😄

**Comment by bjarnef** [comment]
Great with restricting on wheel ranges in https://github.com/Simonwep/pickr/commit/bb5fe04239f6290b4891d103232c1090f94ec123

I think in most cases, developers only need to scroll the alpha channel with a step size of `0.1`, maybe `0.1` or `0.5`. With a precision with 3 decimals the user has to scroll a lot with mousewheel, but maybe it could be configurable with 1 decimal precision as default?

**Comment by Simonwep** [comment]
Unfortunatly, that would go way to much into detail. But you can use these control keys:
`none` -> `0.001` / `1`
`shift` -> `0.01` / `10`
`ctrl` -> `0.1` / `100`

Maybe reversing the decimal sequence? But this would lead to inconsistency :/
