### ISSUE TITLE
Vertical layout?

### ISSUE THREAD

**Issue by dontwork** [Simonwep/pickr#101]
Feature

The UI currently seems suitable only for when displayed horizontally

A vertical option could be made available. Or instructions offered to achieve it,

**Comment by Simonwep** [comment]
You can always use CSS to apply small changes to the layout... the only problem would be changing as you said to horizontal (hue and opacity) slider. I'll work on a option which allows a horizontal (and therefore thinner) layout 😊

**Comment by dontwork** [comment]
@Simonwep yes I have been testing some CSS overrides and have found this one seems to break stuff:

```
.pcr-selection {
  flex-direction: column;
}
```

the main color picker square becomes purely transparent (the checkerboard), when this rule is applied

**Comment by dontwork** [comment]
figma seem to have a good vertical style

![Screenshot 2019-06-08 at 20 03 22](https://user-images.githubusercontent.com/3646471/59151292-879c4080-8a28-11e9-91f3-6d587b9ad99a.png)

**Comment by Simonwep** [comment]
Ha yes, I'm working on themes and this will be the next one :)

**Comment by Simonwep** [comment]
I've added a `sliders` option with which you can define in which direction both the hue- and opacity-slider can be moved:
```js
{
    ...options,

    // Defines the direction in which the knobs of hue and opacity can be moved.
    // 'v' => opacity- and hue-slider can both only moved vertically.
    // 'hv' => opacity-slider can be moved horizontally and hue-slider vertically.
    // Can be used to apply custom layouts
    sliders: 'v',
}
```

Added in 7752202b2fde9311017a93fd695bd603218d4a6c

**Comment by Simonwep** [comment]
@dontwork Themes are [in progress](https://github.com/Simonwep/pickr/tree/theming) and will be published tomorrow :)

**Comment by dontwork** [comment]
Really great work on this tool. Thank you
