### ISSUE TITLE
Prevent closing overlay on focus in color code input

### ISSUE THREAD

**Issue by bjarnef** [Simonwep/pickr#102]
On mobile devices e.g. in Google Chrome on Android it seems when focus in color code input, it shows the virtual keypad, but also close the color picker overlay, so it is a bit hard to see what is being entered in the input field.

**Comment by bjarnef** [comment]
![Screenshot_20190610-124412_Chrome](https://user-images.githubusercontent.com/2919859/59190668-9c3e1d00-8b7d-11e9-9ed8-aae93970c960.jpg)

![Screenshot_20190610-124424_Chrome](https://user-images.githubusercontent.com/2919859/59190678-a102d100-8b7d-11e9-8161-500488b1ba02.jpg)

**Comment by Simonwep** [comment]
Yeah, seem's like an issue. The best would be if the virtual-keyboard opens the input field is above the keyboard.

**Comment by Simonwep** [comment]
Fixed in 1cd2989fb165bc7858c6b523361db0d9a27cdd34. Pickr will now be move to the very top if auto-positioning (without clipping) failed :)
![photo5471933698728372927](https://user-images.githubusercontent.com/30767528/59192616-57b58000-8b83-11e9-9b27-b209768f2843.jpg)

**Comment by bjarnef** [comment]
Thanks for the quick fix. It seems to work much better now.
