### ISSUE TITLE
Add cancel button

### ISSUE THREAD

**Issue by bjarnef** [Simonwep/pickr#106]
#### Do you want to request a **feature** or report a **bug**? 
Feature

#### What is the current behavior?
At the moment it is only possible the reset the color to the current selected color in the themes `Classic` and `Monolith`, but not in the theme `Nano`.

#### What is the expected behavior?
It would be great to be able to add a cancel button, similar to the cancel button in Spectrum color picker https://bgrins.github.io/spectrum/
When clicking this button it reset to the original selected color and close the dialog/overlay. It should of course be possible to customize/localize the button text as it is for the other buttons.

#### Your environment:
```
Pickr-version (see Pickr.version): 1.0.0-beta
Used Pickr-bundle (es5 or normal one): Normal
Browser-version: Version 75.0.3770.90
Operating-system: Windows 10
```

**Comment by Simonwep** [comment]
Yeah that makes sense. Man, you got a ton of ideas so far - that's incredible 😄 I'll take a look at it!

**Comment by Simonwep** [comment]
[done](https://jsfiddle.net/svg48z9a/) :)

**Comment by bjarnef** [comment]
@Simonwep thanks for sharing the jsfiddle :)
While the cancel button does reset the color preview and the "circle" position in the color spectrum, it seems the cancel button doesn't reset the color code in the input?

Original
![image](https://user-images.githubusercontent.com/2919859/59635218-ebbdb380-9150-11e9-8744-0fe0d7314417.png)

Changed to black (#000)
![image](https://user-images.githubusercontent.com/2919859/59635245-055efb00-9151-11e9-9d33-dffb36f3d4fe.png)

Click on cancel button (the color code shows #000000 instead of #FF0000)
![image](https://user-images.githubusercontent.com/2919859/59635275-1871cb00-9151-11e9-9b3a-1316b7ac0af3.png)

**Comment by Simonwep** [comment]
Oh well, you're right - that doesnt seem right

**Comment by Simonwep** [comment]
Well, haha - _never change a running system_ Fixed in 26e7cb9bdfc4c51e1b9190aa14bcec238ee81879

**Comment by bjarnef** [comment]
@Simonwep wonderful, thanks! 👍

**Comment by bjarnef** [comment]
It seems the `cancel` button text is missing from docs?
https://github.com/Simonwep/pickr#options

**Comment by Simonwep** [comment]
@bjarnef See `components.interaction.cancel`: cancel is below save :)

**Comment by bjarnef** [comment]
@Simonwep yes, but not shown under `strings` :)

**Comment by Simonwep** [comment]
Ow you're right

**Comment by Simonwep** [comment]
Updated :)

**Comment by MRVDH** [comment]
On monolith the cancel button calls the "save" event and does not close the window. It does reset the color though.

**Comment by Simonwep** [comment]
Cancel should not close the window, it's a copy of clicking the previous color in the classic theme. And the themes are just design, if there a bug in one - it's in all. Can you reproduce the issue in a JSFiddle?

**Comment by MRVDH** [comment]
Hmm okay, it might be something on my end because I've noticed that things like the `appClass` property don't work either. (the given class is not applied). I'll investigate a bit more.

**Comment by Simonwep** [comment]
@MRVDH Yeah, that does not sound correct. But if you catch any incompatibility raise an issue and I'll try my best to fix it :)
