### ISSUE TITLE
projects that use pickr

### ISSUE THREAD

**Issue by diomed** [Simonwep/pickr#109]
would be nice to see list of projects which use pickr

**Comment by Simonwep** [comment]
Will be added :)

**Comment by av01d** [comment]
https://www.photofilters.com
(and some more I will mentions as soon as #112 is fixed)

**Comment by Simonwep** [comment]
According to npm and my reddit post: 
* ember-pickr ([npm](https://www.npmjs.com/package/ember-pickr) / [github](https://github.com/astronomersiva/ember-pickr#readme))
* ngx-pickr ([npm](https://www.npmjs.com/package/ngx-pickr) / [github](https://github.com/yharaskrik/ngx-pickr))
* [groovy-menu](https://groovymenu.grooni.com/) (no idea what this is, seems like a word-press plugin but there is no demo or such a thing)

A very old version is also used by https://paperbits.io/

**Comment by av01d** [comment]
https://www.printscreenshot.com
https://www.photoresizer.com
(more to follow, I'm still working on 2 sites that use pickr, should both be online before the end of July)

**Comment by diomed** [comment]
I think that the biggest issue here are projects that don't use pickr, and they should.:D

**Comment by varunsridharan** [comment]
Soon this project will be used by https://github.com/wponion/wponion :-)

**Comment by okydk** [comment]
https://grid.studio 😘

**Comment by Simonwep** [comment]
@okydk Nice app, I've seen the initialization of Pickr is kinda messed up, do you use the latest version? If not you may open an issue or explain how you integrate it (The environment where pickr spawns etc.)

**Comment by okydk** [comment]
@Simonwep Thanks! Currently running on the old NPM version, but new version is coming soon - with latest version of your pickr! 🙏

**Comment by NateSeymour** [comment]
A wiki page with projects that use `pickr` is in consideration. Otherwise, this issue appears to be closed.

Have a wonderful day! :)
