### ISSUE TITLE
how to get the value using jquery?

### ISSUE THREAD

**Issue by slfan2013** [Simonwep/pickr#110]
How to use the JQuery to get the color value?

In this [jsfiddle](http://jsfiddle.net/bqmh9tu4/), I am trying to use `$("#colorvalue").text($("#test").val())` to get my color values, e.g. `#000000`. However, if you see the console log, the `$("#test").length` is surprisingly 0.  It seems that the `new Pickr()` somehow removed the `#test` and replaced it with something else. Anyway, is there a way to use JQuery to return the color value? Or how the color values should be returned?

Thank you for the great package! I love it.

**Comment by Simonwep** [comment]
You can use `pickr.getColor().toHEXA()` to get the current HEX color value as array (e.g. `['ff', 'fa', 'fb']`), or `pickr.getColor().toHEXA().toString()` to get it as string value (e.g. `#fffafb`). 

The element you pass to pickr gets _replaced_ with pickr, so after initialization `.color-picker` wont exist anymore. I think I know what you want, checkout this updated fiddle: http://jsfiddle.net/z2qd3jkf/

You also used a really, really old version. Be sure to load the latest one :)

**Comment by slfan2013** [comment]
Thank you for the prompt reply. It works fine. 

Yet, I think it could be more convenient if the replaced pickr can inherit the original id of the `div` so that it can be caught by id. I am asking this is because I will have dynamically multiple pickrs in the page and I would like to return the value of any of the pickr when it changes, instead of having a callback function for each of the pickrs.

**Comment by slfan2013** [comment]
I would like to reopen this question. Is there a way of getting the color by div ID or anything? Suppose I have two pickr on a page and I would like to get the color of each of them using jquery or pure javascript. Is it possible?

**Comment by Simonwep** [comment]
What are you trying to achieve? You need at least the instance of pickr to get a color.

Pickr is completely independent of any framework or library, if your are using JQuery as dom-selector or d3 makes no difference :) You can get the current color of each by just calling `getColor()` on a pickr instance. Take a look at the [methods](https://github.com/Simonwep/pickr#methods) section in the docs.

Just create two pickr instances and you're done. Take a look at [this fiddle](http://jsfiddle.net/Simonwep/412zv9g0/)

**Comment by slfan2013** [comment]
I just have multiple pickr on the page. Each pickr has its corresponding dynamically created id. I just would like to use jQuery to get any pickr color I want using the ids.

**Comment by Simonwep** [comment]
Why don't you have a centralized place where you store your instances / application state? You need to initialize pickr somewhere, therefore you got the instance stored in a variable on your page or bundle. Pickr isn't meant to polyfill or enhance a native HTML5 feature like `input[type=color]`. 

I can't imagine a situration where you don't have access to the pickr instance anymore... The only possible solution would be to wrap pickr into a web-component, then you could "access" it via `document.getElement`

**Comment by Simonwep** [comment]
I'll close this for now. Re-open if you have any questions.

**Comment by nomanshabb** [comment]
calling initSimon wep picker two times at same page reset the value in edit scenario
