### ISSUE TITLE
Default theme is broken

### ISSUE THREAD

**Issue by av01d** [Simonwep/pickr#111]
In the latest version of pickr, the default theme is broken. Check for yourself here:
https://jsfiddle.net/av01d/mdbfck5g/

<img width="361" alt="pickr-bug" src="https://user-images.githubusercontent.com/6247646/60098402-c7b43080-9755-11e9-86ac-6c06bfc6a4a1.png">

Interface elements are shown before the window is opened, and the pickr does not appear when I click the button. 
This does work for the other themes (monolith & nano).

Using pickr version 1.1.1 (living on the edge)

**Comment by av01d** [comment]
Aha... mystery solved. You need to include the `default.min.css` style file, which gets you... wait for it... a theme named `classic`! 👎 
While `monolith.min.css` provides a `monotlith` theme, `nano.min.css` provides `nano`.
Please be consistent: either rename `default.min.css` to `classic.min.css`, or simply rename this theme to `default`.

**Comment by Simonwep** [comment]
I'll rename it to `classic.min.css`.

**Comment by av01d** [comment]
Thanks!
