### ISSUE TITLE
Very odd scrolling behavior

### ISSUE THREAD

**Issue by av01d** [Simonwep/pickr#112]
Check this: https://jsfiddle.net/av01d/7e9mo1rg/
And this: https://jsfiddle.net/av01d/9p6cesau/

Scroll the result-window until the little colored div is in view. 
Click it to open the color picker. It opens on the weirdest places.
Also: scrolling the page while the picker is open creates even more weirdness.
Why not "stick" the pickr to the element (here: `#color-pickr`) that opens it?
Or do I miss a config option?
It seems like this behavior is over-engineered, while it should be very simple?

Again using 1.1.1. Issue tested on Firefox an Chrome.

**Comment by Simonwep** [comment]
Implementing a positioning engine is a pain in the ass. And I try to not depend on any third-party libraries such as popperjs as good as I can. There are many many edges cases and differed user expectations which should be satisfied, including precisely defining where and how this widget should appear. 

I've updated your fiddles with the fixed version:
https://jsfiddle.net/jgadnq6v/ and https://jsfiddle.net/Lzd6ycn4/

Thank you for your contribution.

**Comment by av01d** [comment]
Wow Simon, that's F-A-S-T!!! Thanks so much, this is indeed the fix I was looking for.
Keep up the good work!!!

**Comment by Simonwep** [comment]
No problem, It's crazy enough that nobody noticed it so far. I've bumped the version to 1.1.2 where this is fixed :)

**Comment by av01d** [comment]
I am using pickr in quite a few sites, sites that are quite popular too. I need to fix them with this new pickr version, when that's done I'll let you know what sites they are.
