### ISSUE TITLE
Gradient Support

### ISSUE THREAD

**Issue by varunsridharan** [Simonwep/pickr#119]
## Do you want to request a **feature** or report a **bug**? 
**Feature Request**

Do you have any idea for adding gradient support ? if so when it could be ?

### Example
![image](https://user-images.githubusercontent.com/1884287/61178022-07599400-a601-11e9-862e-cada460a9754.png)

http://tutsville.com/docs/coloringpick-jquery-gradient-color-picker/

**Comment by Simonwep** [comment]
This would be at least double the bundle size. Pickr is even now kinda heavy (Around 10Kb zipped). This may be something which could be done on top of pickr (You could use pickr as color-pickr and a additional library to justify your stops etc.)

**Comment by varunsridharan** [comment]
@Simonwep awesome thanks for your quick response. well since i am not a good js developer i have to wait untill some one could help me on this. but again your project is great and for sure i will be using it. in my WordPress Framework (WPOnion) 😄

**Comment by ryanlin1986** [comment]
Cann't find a gradient color picker for now, really expecting a gradient color picker.

**Comment by varunsridharan** [comment]
@Simonwep is it possible to create gradient as a add-on which can be in a separate file ?
I am not good at JavaScript. If not I would have contributed to this project by creating gradient picker
For now I can contribute by testing

**Comment by Simonwep** [comment]
There won't and shouldn't be any direct extensions to pickr (regarding the core). Pickr should stay as it is since any more "bigger" features would increase the bundle size significantly (And the complexity would way to big as everything is written in vanilla js). 

But I'm currently working on a small widget which is build _on top_ of pickr (uses it as dependencies) which could be used for this purpose. I'll update this thread if there are any news, should be in the next days ;)

**Comment by varunsridharan** [comment]
Awesome :-) well what i meant as a addon is something like dependencies which can be installed by the user as a separate package even if this addon not exists the core Pickr would work. this is what i meant :-0

**Comment by Simonwep** [comment]
Oh okay :) Yeah, but I'd separate it into another package. Pickr's API is big enough to easily build things on-top of it without the access to the core.

Here is a quick demo of such a thing: https://simonwep.github.io/gpickr/index.html

@ryanlin1986 I won't have enough time to properly maintain it. If you want you could support me via. patreon - I already do my best to maintain the existing ones.

**Comment by varunsridharan** [comment]
@Simonwep you are awesome man :-) you really did a great job.

**Comment by varunsridharan** [comment]
@Simonwep i am unable to access the repo
And here some feedback

1. The gradient pointer could be bit bigger 
![image](https://user-images.githubusercontent.com/1884287/61232500-0bde9380-a74c-11e9-89c0-c876d5394e04.png)

**Comment by Simonwep** [comment]
Whoops, I made it public :)

**Comment by ryanlin1986** [comment]
That's great to see the gradient picker already here

**Comment by varunsridharan** [comment]
@Simonwep as a open source developer I can't afford much but I did what I could do 😀
You don't know how much it means and you really did a big contribution towards WPonion project that I am working on. 

FIY : I have been searching for a gradient picker for almost 2yrs now but I did not found anything useful

You are some super power 💪💪 created something in just in time..
You are great. Keep doing what you are doing 😀😃

**Comment by eldos777** [comment]
![Untitled](https://user-images.githubusercontent.com/22207958/62286721-efde3000-b475-11e9-9057-f7f5c6c57cd5.png)

I created gradient

**Comment by varunsridharan** [comment]
@eldos777 using ?

**Comment by Simonwep** [comment]
@eldos777 I'm also interested, I think the easiest way would be to just enhance gpickr as it is haha

**Comment by eldos777** [comment]
@varunsridharan : Writed code for gradient feature.

**Comment by varunsridharan** [comment]
@eldos777 ok. but confusing 😕 why not explain bit more ?

**Comment by NateSeymour** [comment]
With the creating of `gpickr`, this topic appears to be resolved within the scope of `pickr`.

Please continue all gradient related discussion here: https://simonwep.github.io/gpickr/index.html, and have a wonderful day! :)
