### ISSUE TITLE
Hex 8 character alpha channel

### ISSUE THREAD

**Issue by joeKingtheThird** [Simonwep/pickr#12]
I suppose you could have the hex value with the alpha channel - 8 digits for web development. You'd have 6 digits with the alpha at 100% or whatever 255? Then if it is less then have an 8 digit hex.

**Comment by Simonwep** [comment]
Currently, if you have a alpha channel, it will be cuttet off in the hex-representation. 
Moreover it seems like it has only partial support. It's part of the [CSS-4 spec](http://lists.w3.org/Archives/Public/www-style/2013Apr/0051.html) so I wouldn't support it until CSS-4 has good support. But if many people want it I can add it.

**Comment by joeKingtheThird** [comment]
firefox and chrome support 8digitchex - https://caniuse.com/#feat=css-rrggbbaa

**Comment by MoritzBru** [comment]
Nice addition ;)
But it is not possible to type in 4- or 8-digit hex color in the textfield

**Comment by Simonwep** [comment]
@MoritzBru I will add it today! :)

**Comment by Simonwep** [comment]
Finally this is also possible, see de80ec6f4bdfa1574f7084ffe59d0e8dbdf001bf.
