### ISSUE TITLE
SCSS Source Compile Issue

### ISSUE THREAD

**Issue by varunsridharan** [Simonwep/pickr#122]
I am using this library in (WPOnion) in where i wanted to provide full support for this library in my project and i do not want to load all css files  so in our project we have a file called `wponion-plugins.css` where most of the plugins css are combined to 1 file.

when i try to use the below scss code 
```scss
@import "../../../node_modules/@simonwep/pickr/src/scss/base";
@import "../../../node_modules/@simonwep/pickr/src/scss/themes/classic";
@import "../../../node_modules/@simonwep/pickr/src/scss/themes/monolith";
@import "../../../node_modules/@simonwep/pickr/src/scss/themes/nano";
```

i can see that `@simonwep/pickr/src/scss/base` source has been repeated. as the same files is included in all the themes file.

so i would request if its possible to remove the ` @simonwep/pickr/src/scss/base` include in all the theme files or create a separate file something like below

**classic-dist**
```scss
@import '../lib/variables';
@import '../lib/mixins';
@import '../base';
@import 'classic-theme';
```

**Comment by Simonwep** [comment]
If you take a look into each theme, you can see that all requirements are already imported:
![image](https://user-images.githubusercontent.com/30767528/61372956-be237180-a898-11e9-8d20-39c16fdcef2d.png)
So importing each theme like this should work:
```scss
@import '~@simonwep/pickr/src/scss/themes/classic';
@import '~@simonwep/pickr/src/scss/themes/monolith';
@import '~@simonwep/pickr/src/scss/themes/nano';
```

On build-time each theme get's compiled idependent of each other so importing each like above *must* work (see [this build snipped](https://github.com/Simonwep/pickr/blob/master/scripts/build.js#L17)) :)

**Comment by varunsridharan** [comment]
@Simonwep I did took a look at it before ..
Here is the output based on your idea of importing all theme's css into a single file
https://pastebin.com/nJpvkkZL
in that above link you can find contents inside `base.scss` file repeated multiple times

### My SCSS Code
```scss
//@import "../../../node_modules/@simonwep/pickr/src/scss/base";
@import "../../../node_modules/@simonwep/pickr/src/scss/themes/classic";
@import "../../../node_modules/@simonwep/pickr/src/scss/themes/monolith";
@import "../../../node_modules/@simonwep/pickr/src/scss/themes/nano";
```
### CSS output : 
Please do check the link above for clear view
https://vsp.ams3.cdn.digitaloceanspaces.com/sshots/i/2019/Jul/17/1563364767-183.jpg
![image](https://user-images.githubusercontent.com/1884287/61373862-947a4280-a8b8-11e9-98a6-fbe2133c8837.png)

**Comment by Simonwep** [comment]
Every css bundle is completely independent to allow the user to import any theme without needing to import a _base_ css. I understand your case, of course - if you import more than one theme around 90% are only duplicate style declarations (I've copied / pasted a lot while making themes, around 95%...). 

Overriding styles means throwing away savable bandwidth, I tried to bring that into perfection by providing a single theme file for each theme which is ~100%.
![image](https://user-images.githubusercontent.com/30767528/61379997-e31fe080-a8a8-11e9-9bbc-e978f2fc096a.png)
(The `1.7%` is a flex fallback fro browser which don't support grid)

And you're right, currently it's absolutely not _optimized_ regarding bundle size if you import more than two themes. I'll try to find a solution to it :)

**Comment by Simonwep** [comment]
The themes are now (if bundled together) near-perfect if you load them all in (regarding bundle size).  Done in bb407e7e5aaba982a25f3bed1117db38479a4659 and 68ad6da78bf72caa4534e89ef6683f438c06b538. Altogether you get around `14kb` which is pretty small since each theme is around `8.5kb` :)

**Comment by varunsridharan** [comment]
@Simonwep in your above comment do you mean that it's done?

if it's don't think so.

https://github.com/Simonwep/pickr/blob/master/src/scss/themes/classic.scss#L3
https://github.com/Simonwep/pickr/blob/master/src/scss/themes/monolith.scss#L3

in each theme, you still included `../base` which basically compiles with all basic CSS under `../base` for each theme and it's not still optimized for bundles.

**Comment by Simonwep** [comment]
node-sass will remove duplicates. Otherwise the mentioned `14kb` would be `3 * 8.5kb` (e.g. 25.5kb)

**Comment by varunsridharan** [comment]
@Simonwep sorry i can't understand what you mean.

**Comment by Simonwep** [comment]
node-sass will remove the duplicate import's of base automatically, just try it :)
