### ISSUE TITLE
Difficult to handle open/closed state on pickr button

### ISSUE THREAD

**Issue by makepanic** [Simonwep/pickr#125]
Hi, thanks for creating this great library.

#### Do you want to request a **feature** or report a **bug**? 

* feature

#### What is the current behavior?

Right now pickr only adds the `visible` className to `.pcr-app`.
Sadly this makes it impossible to style the pickr button (or element, given `useAsButton=true`).

#### What is the expected behavior?

I would like to have some kind of className that toggles on the pickr button element.
That way it's possible to style the pickr button (or element, given `useAsButton=true`) depending on its open state.

Alternatively some additional show/hide events could be helpful so a consumer is able to implement the visibility change handling themselves.

#### Your environment:
```
Version (see Pickr.version): 1.2.3
Used bundle (es5 or normal one): es5
Used theme (default is classic):  nano
Browser-version:  chromium 75
Operating-system:  linux
```

**Comment by Simonwep** [comment]
Great idea! I like the idea with additional events, I'll take a look at it :)

**Comment by Simonwep** [comment]
I've added `hide` and `show` events in 18be8c9e48a7e598e93ea1350157898f66746066. All other option would blow the code too much but you can chain all event-listeners so it won't be that much code you need to write :)

**Comment by makepanic** [comment]
Thanks :D

**Comment by Simonwep** [comment]
If nothing comes up in the next 2/3 days :)
