### ISSUE TITLE
Adding custom value to input

### ISSUE THREAD

**Issue by mmativ** [Simonwep/pickr#133]
#### Do you want to request a **feature** or report a **bug**? 
Bug

#### Your environment:
```
Version 1.2.6
Used bundle (es5 or normal one): Normal
Used theme: classic 
Browser-version:  Chrome
Operating system:  macOS Mojave
```
Hello, when i tried to add a custom value into input E.g. `#f3f3f3`, there's no way to add the custom hex value because on when typing, after 3 digits the auto-complete happen, there's any way to ignore auto-completion?

**Comment by Simonwep** [comment]
Fixed in 973f3174cc43c97bd437f79d1767aaeb962207a2 :)
