### ISSUE TITLE
Container option missing

### ISSUE THREAD

**Issue by mafar** [Simonwep/pickr#138]
Hi, 
I see that there is no ```container``` option and it makes complex usecases more difficult.

it is not sufficent to append app in ```body```
in most complex cases , users need ```specific container```  so that they can clear it as needed and so  that they dont clutter the body with dom overloading

in my case, i have layouts, each layout has tabs and inside tabs there are layouts again , consider it an engineering aap , and each tabs maintains its containers and removes them on tab close

In my usecase , Nothing is appended to body, instead it is appended to specifc containers.

**For example:**
see bootstrap-select -> option -> container
https://developer.snapappointments.com/bootstrap-select/options/
This solves much of problems for users where you dont force them for body only

**Comment by mafar** [comment]
see here
It does not break existing code !!!
By default ``` {'container':'body'} ``` , so it works out of box

https://github.com/Simonwep/pickr/compare/master...mafar:patch-1

**Comment by Simonwep** [comment]
Thank's :) I'll take a look at it!
