### ISSUE TITLE
Support RTL and i18n

### ISSUE THREAD

**Issue by KiarashS** [Simonwep/pickr#14]

**Comment by Simonwep** [comment]
Is available since f7c85b6952070b1c93437c4da5780f6c4e50fe86 and ca9e328fd07e1851218a2e76211caa0526156e39. There's also a new version [0.1.4](https://github.com/Simonwep/pickr/releases/tag/0.1.4) which includes this extension :)

**Comment by KiarashS** [comment]
@Simonwep There is a good news! Thanks... ;-)
