### ISSUE TITLE
Add color when custom input changes

### ISSUE THREAD

**Issue by gokhan17** [Simonwep/pickr#141]
Hello,
How do I set the color code entered in the input field? 
("setColor" method or different option...)

#### Screenshot:
<img width="486" alt="color-picker-question-ss-2" src="https://user-images.githubusercontent.com/8653288/63508138-ff372300-c4e1-11e9-9986-413735e281d7.png">

Thank you for the great package. 👍

**Comment by Simonwep** [comment]
You're welcome :)
You can use the `keyup` event to listen for changes on the input field, and use `pickr.setColor` to apply the color!
Use `true` as second arg for `setColor` to also apply it to the button.
E.g.

```js
inputEl.addEventListener('keyup', ({target}) => {
    pickr.setColor(target.value, true);
})
````
Should do the job (not tested though)

**Comment by gokhan17** [comment]
Thanks for the answer.
I want to do this:
#### Input Value => Set Value:
**#fff** => #FFFFFF
**red** => #FF0000
**lelelelelele** (Invalid Color Code) => #000000

and more... (like pickr original input)

<img width="635" alt="color-picker-question-ss-3" src="https://user-images.githubusercontent.com/8653288/63534781-a2a32a80-c518-11e9-95ac-57cb76b6e24c.png">

**Comment by NeonNature** [comment]
I was looking a similar solution with custom inputs for a week now and never thought the community is still alive. 

Mine seems to be running an infinite loop according to the console.

I usually end up to #42445A (which, I think, is Pickr's default color) and some random value when I bind both. 

```
  Pickr.on('change', color => {
               $("#"+name+"BColor").val(Pickr.getColor().toHEXA().toString());
            });

   $('#'+name+'BColor').on(' paste keyup', function(){
                const sColor = $('#'+name+'BColor').val();
                Pickr.setColor(sColor, true);
            });
```

I've tried `input` event but I still get the wrong color code in the input box.

(The Pickr button and the color code inside the Pickr displays the right one though)

**Comment by Simonwep** [comment]
@gokhan17 It's covered in #140. Will be fixed with that one :) Currently invalid colors get resetted and `no color` dosn't causes `getColor` to return null which is both kinda buggy.

**Comment by gokhan17** [comment]
@Simonwep I solved it with the "getColor" function. Thanks :)

**Comment by NateSeymour** [comment]
This issue appears to be resolved. If you have any more problems, please let me know and I'll reopen it.

Have a wonderful day :)
