### ISSUE TITLE
[request] livePreview : true/false  Option

### ISSUE THREAD

**Issue by mafar** [Simonwep/pickr#142]
For reference demo : https://github.com/Sphinxxxx/vanilla-picker

It will be helpful to add new option 
```js
{
livePreview : true // false
}
```
which applies changes to picker and triggers save event 
This is becuase most of users are not fan of clicking save button and they just want job done while picking color. 

This will make save button optional for user as it is already becuase changes are applied and saved on the go

**Comment by Simonwep** [comment]
Take a look at the [readme](https://github.com/Simonwep/pickr#options), it's already there. It's named `comparison`.
