### ISSUE TITLE
Binding with input

### ISSUE THREAD

**Issue by mafar** [Simonwep/pickr#143]
I am trying to bind pickr with html input text .

https://codepen.io/mafar/pen/pozNeeB?editors=0010

**Requirements**:
input value whould be updated when 

1. changes by mouse/touch ```change event```
1. RGBA/HEXA input is changed   ```change event```
1. when cancelled ```cancel event```
1. when cleared  ```clear event```

**Issue:**
**RGBA/HEXA input is changed**
When i focues input and use key board arrows keys , left and right, change event is triggered while actual color is not yet changed

**when cancelled ```cancel event```**
when i make changes and press cancel , how do i get value of color which instance currenlty has ? becuase ```instance.getColor().toHEXA().toString()``` gives me value before cancellation 

 ```
    .on("cancel", function(instance) {
      current_color = instance
        .getColor()
        .toHEXA()
        .toString();
      console.log("cancel", current_color);      
    })
```
![ff](https://user-images.githubusercontent.com/4101480/63849298-a682e280-c946-11e9-954f-2705dfba447f.gif)

**Comment by mafar** [comment]
I thought since i have ``` comparison: false,``` which is equal to live preview , changes are saved on the go ??

**Comment by NateSeymour** [comment]
In your codepin, the changes are saved as the user inputs them. However, when the user presses cancel, the color is reset. This is intended behavior and I'm sorry, but I am failing to see what else a cancel button should be doing when pressed. 

This is intended behavior and not a bug.

**Comment by mafar** [comment]
> In your codepin, the changes are saved as the user inputs them. However, when the user presses cancel, the color is reset. This is intended behavior and I'm sorry, but I am failing to see what else a cancel button should be doing when pressed.
> 
> This is intended behavior and not a bug.

Plz consider following steps:

1. Initially value of input is ```#FF0000``` , pickr is initialsed with this value as well
2. pickr is initialsed with ```comparison: false,``` , so changes are appied as color is changed by mousedown
2. I move mouse and change value to other than ```#FF0000```, lets say '''#402C2C```, pickr button color is changed instantly and input value is changed correspondingly to ```#402C2C``` becuase of ```
3. Now i press cancel button, pickr changes color to ```#FF0000``` since it was inited with this value
4. Now input still has ```#402C2C``` and there is no way of knowing on cancel what values should be applied to input

Becuase ```cancel click``` only triggers ``` cancel event ```,
```save event```  or ```chaneg event``` are not triggered
How do I know to which color ```pickr``` has revereted to ??? so that i can put that value input as input lost its original value becuase changes were being done instantly ?

I hope this clearifies my issue. Thankx

**Comment by NateSeymour** [comment]
@mafar, Okay, I believe I understand your problem now. Everything that you have described until now has, in fact, been documented intended behavior. Again, please read the documentation.

You can access the latest saved color from `onCancel` like this:

```
.on('cancel', (color, instance) => {
	const myHEXAValue = instance.getSelectedColor().toHEXA();
});
```

We will not be triggering `onSave` or `onChange` when the user cancels: this is not what they are for and it would cause performance issues and break existing implementations.

Before continuing to contribute, please read the following documents/comments and acknowledge that you have done so:

https://github.com/Simonwep/pickr/blob/master/README.md
https://github.com/Simonwep/pickr/blob/master/.github/CONTRIBUTING.md
https://github.com/Simonwep/pickr/issues/140#issuecomment-524389036
https://github.com/Simonwep/pickr/pull/144#issuecomment-525783341

**Comment by mafar** [comment]
Thankx , works now expected
https://codepen.io/mafar/pen/pozNeeB?editors=0010
