### ISSUE TITLE
Pass padding prop through to Nanopop on instantiation.

### ISSUE THREAD

**Issue by ljsnagy** [Simonwep/pickr#145]
#### Do you want to request a **feature** or report a **bug**? 
feature

#### What is the current behavior?
Nanopop has a custom padding option, but it's not passed through on instantiation. If you want to set a custom padding for positioning you have to overwrite the nanopop instance on the pickr.
```js
const { button, app } = pickrInstance._root;
pickrInstance._nanopop = Pickr.libs.Nanopop({
  el: app,
  reference: button,
  padding: 12,
});
```

#### What is the expected behavior?
Should be a prop like the other config options passed on instantiation. E.g.
```js
const pickr = new Pickr({ el: '.my-picker-btn', padding: 12 });
```

I can do a PR for this if need be.

**Comment by Simonwep** [comment]
Added in 1e3e1f2d1afa0813c801effc2d2c33f8ef81ea32 :)
