### ISSUE TITLE
Windows Defender thinks Pickr is a virus

### ISSUE THREAD

**Issue by Lars-** [Simonwep/pickr#146]
#### Do you want to request a **feature** or report a **bug**? 
bug

#### What is the current behavior?
I can't download it (1.4.0)

#### What is the expected behavior?
That I can download it

#### Your environment:
```
Version (see Pickr.version): 1.4.0
Used bundle (es5 or normal one): n/a
Used theme (default is classic): n/a
Browser-version:  Chrome (latest)
Operating-system:  Windows 10
```

Virus found: Trojan:Win32/Sprisky.U!cl
Severity: High
File: C:\Users\[username]\Downloads\pickr-1.4.0.zip->pickr-1.4.0/dist/pickr.es5.min.js

Why does this come up?

**Comment by NateSeymour** [comment]
Oh it is! Thanks for your credit card information, by the way ;)

---

Just kidding!

Please see this article: https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Trojan:Win32/Sprisky.U!cl

It seems to be part of Windows Defender's new machine algorithms, meaning that we may see a lot more false positives in the future. Unfortunately, there is little at `pickr` that we can do to fix this bug in Microsoft's software. 

I'd recommend that you turn off Windows Defender temporarily or add a rule to ignore the folder that `pickr` is downloaded to.

Have a great day!
