### ISSUE TITLE
default color can not have an rgba with an alpha of 0

### ISSUE THREAD

**Issue by CptMeatball** [Simonwep/pickr#149]
#### Do you want to request a **feature** or report a **bug**? 
Bug

#### What is the current behavior?
If the default value of the pickr has an alpha of 0, it shows a black rgba value. `rgba(0,0,0,1)` as a default.

#### If the current behavior is a bug, please provide the steps to reproduce and create a 
Set default to a rgba representation and set a default RGBA value with an alpha of 0.

https://jsfiddle.net/kxauvfnm/2/

#### What is the expected behavior?
Default picker color should be of 0 alpha.

#### Your environment:
```
Version 1.4.1
Used bundle: Normal
Used theme: Nano
Browser-version:  Chrome 76.0.3809.132
Operating-system:  MacOS 10.14.6
```

**Comment by NateSeymour** [comment]
Thanks for bringing this to our attention! The issue has been fixed in fde3615. Let me know if you have any other questions/concerns/comments.

Have a great day!
