### ISSUE TITLE
Add destroy method

### ISSUE THREAD

**Issue by retyui** [Simonwep/pickr#15]
**feature**
I'm doing integration with the react, since there is no way to clean the event handlers after this meaningless work (

**Comment by Simonwep** [comment]
What to you mean exactly, to remove all event-listeners from the components which pickr has? Or only from the button?
If you want to remove the entire widget it you could do something like: 
```javascript
const root = pickr.getRoot().root; // Root element from pickr
root.parentElement.removeChild(root);
```

**Comment by retyui** [comment]
I understand, 
But a can't remove this handles:
https://github.com/Simonwep/pickr/blob/5863f8e4bd04e06700846c906ffaded407b34a93/src/js/pickr.js#L190-L193
https://github.com/Simonwep/pickr/blob/5863f8e4bd04e06700846c906ffaded407b34a93/src/js/pickr.js#L221-L222

**Comment by Simonwep** [comment]
Oh, okay. I see, it is highly probable that I will add this. Good point!

**Comment by Simonwep** [comment]
Yeah, I've added it. see 71b38fc7a8b4ed26fd5b207b184f043e6d61fb3a.
I'ts currently in no release but if you want to use it now, here's a short documentation:
* pickr.destroy()`:HSVaColor` _- Destroy's all functionality._
* pickr.destroyAndRemove()`:HSVaColor` _- Destroy's all functionality, moreover it removes the pickr element including the button._
