### ISSUE TITLE
Wrong keyboard mappings on the color palette.

### ISSUE THREAD

**Issue by azaslonov** [Simonwep/pickr#150]
Hi there,

Here's a couple of problems that affect accessibility requirements:

1. When focused on the color palette, the selection goes down even if a user presses "Up" arrow button. Basically, it's impossible to go up with the keyboard.

2. In "classic" theme, vertical sliders (i.e. "opacity") do not respect "Up" and "Down" arrow keys, only "Left" and "Right" (which is confusing for users).

```
Version (see Pickr.version): 1.4.1
Used bundle (es5 or normal one): Normal
Used theme (default is classic):  Classic
Browser-version: Chrome
Operating-system: Windows 10
```

**Comment by Simonwep** [comment]
Fixed in de3023297984000e0904bf7037b17eca02376d8c and 0738dcd6c82710af421bd896674f8c15b5a9d71b :)
