### ISSUE TITLE
Regression, values like rgba(163, 47.000000000000014, 59.00000000000005, 1)

### ISSUE THREAD

**Issue by AwokeKnowing** [Simonwep/pickr#151]
I've used picker for a while.  I recently updated to 1.4.1 from 0.4.   I remember back near 0.3 there was a bug where values we not 'rounding', and it was fixed.   Now, I updated and I'm seeing those values again.  I'm using classic theme.  I'm also using the es5 minified version

I'm calling it a regression bug.

**Comment by NateSeymour** [comment]
That was a bug that you could use decimal places in `rgba()` values, because they do not exist in `rgba()` and were as such removed.

I am not able to replicate the issue that you are having. Please provide a demo demonstrating it and in the future, do not delete the issue template.

**Comment by AwokeKnowing** [comment]
I apologize for deleting the template.

to clarify, the box showing rgba value is correctly rounded in the box at lower left, but when the values are retreived, they have their 'unrounded' form:

![image](https://user-images.githubusercontent.com/2770322/64550881-b1475b00-d2e8-11e9-89cb-cf738984c4e6.png)



![image](https://user-images.githubusercontent.com/2770322/64550985-f2d80600-d2e8-11e9-8faa-816079bebe5a.png)

**Comment by NateSeymour** [comment]
This is expected behavior, please see here: https://github.com/Simonwep/pickr#the-hsvacolor-object

To retrieve the values without their decimal places, you can pass zero to `toString()` as such:

`hsva.toRGBA().toString(0)`

Have a great day!

**Comment by AwokeKnowing** [comment]
Thanks! that fixed it.
