### ISSUE TITLE
Button color not updating on iOS Safari

### ISSUE THREAD

**Issue by kkeith-adg** [Simonwep/pickr#153]
#### Do you want to request a **feature** or report a **bug**? 
Bug

#### What is the current behavior?
Choosing color and hitting save doesn't update button color on iOS Safari.

#### If the current behavior is a bug, please provide the steps to reproduce and create a [JSFiddle](https://jsfiddle.net/Simonwep/qx2Lod6r/).

Go to demo page in Safari on device running iOS 12.1 (iPad Gen 6 in my case) and select color and save. Nothing happens with button color.

#### What is the expected behavior?
Button should update to selected color. When applying default color externally, it should update the button as well.

#### Your environment:
```
Version (see Pickr.version): 1.4.2
Used bundle (es5 or normal one): normal
Used theme (default is classic):  all
Browser-version: Safari 12.1
Operating-system:  iOS 12.1 on iPad Gen 6
```

#### Additional Notes
The main functionality seems to work fine. When I set the default color from my app, it doesn't show in the button like it does on a desktop browser, but it is correctly set in the modal. You can change the color and save which will produce the proper color, just not update the button UI.

On all the desktop browsers I've tried, the button color shows properly.

**Comment by NateSeymour** [comment]
Thank you for bringing attention to this issue! :)

It has been fixed in commit 6a3c90, please let us know if you are having any more problems.

Have a wonderful day!
