### ISSUE TITLE
Cannot import as ES6 module

### ISSUE THREAD

**Issue by eddieherm** [Simonwep/pickr#154]
#### Do you want to request a **feature** or report a **bug**? 
Bug
#### What is the current behavior?
Cannot import Pickr as an ES6 module on the browser side.
`import Pickr from '/extlib/pickr/pickr.min.js';` results in this error: `Uncaught SyntaxError: The requested module '/extlib/pickr/pickr.min.js' does not provide an export named 'default'`
#### What is the expected behavior?
Should be able to import as a module.
#### Your environment:
```
Version (see Pickr.version): 1.4.2
Used bundle (es5 or normal one): normal
Used theme (default is classic): nano
Browser-version:  Chrome 77.0.3865.90
Operating-system:  Win 10
```

**Comment by NateSeymour** [comment]
`Pickr` is not designed to be imported as an ES6 module in the browser as stated in the documentation. In the browser, you will need to import it with a `script` tag in HTML. 

For more information, please refer to the README.

Have a great day :)

**Comment by eddieherm** [comment]
Ok. I didn't see any explicit reference to ES6 modules in the docs. Thanks for the update.
