### ISSUE TITLE
setColor without triggering change events?

### ISSUE THREAD

**Issue by derklempner** [Simonwep/pickr#155]
Hi, thanks for this great colour picker! :) 

I may be missing something obvious, but is it possible to set the colour (and update the UI elements) _without_ firing any of the event handlers?

**Comment by NateSeymour** [comment]
At the moment, unfortunately, there is not. 

Out of curiosity, what is it exactly that you are trying to do? Maybe I can help you find a better solution :)

**Comment by derklempner** [comment]
No worries, thanks for the quick reply, I worked around it with a flag in my handlers and it's all working nicely :)

I was trying to set the background of different divs with a single picker, here is a crude example.. maybe I am doing something silly : https://jsfiddle.net/0tso9q43/2/

**Comment by NateSeymour** [comment]
Glad you got it figured out!

Please let me know if there is anything else that I can do to help you :)

**Comment by emafriedrich** [comment]
@NateSeymour i think that this feature is good.

When i `setColor()` in  mi angular app when a `ng-change` event ocurrs (the user can set the color on a input field, and i wont represent this change on picker) the event is trigered again with undesired efects.
