### ISSUE TITLE
How to post to form when useAsButton = false

### ISSUE THREAD

**Issue by itajackass** [Simonwep/pickr#156]
I don't understand how to retrieve the value from an element color:

    `<input type="text" name="color" id="color">`

initilized with option: useAsButton = false.

When I submit my form, I can retrieve all my $_POST but $_POST['color'] doesn't exist.

Another question:

Is it possible to use a layout like this (from another color-picker example)?

![pickr](https://user-images.githubusercontent.com/17260726/65944594-56f67180-e432-11e9-8f7d-d6b39b073cff.jpg)

Using: useAsButton = true

```
<div class="input-group">
	<input type="text" value="#3788d8" id="color" name="color"/>
	<span class="input-group-addon"><i class="fa fa-square-full"></i></span>
</div>
```

With input box for HEX value and a icon square with color that update on change color from the picker?

**Comment by NateSeymour** [comment]
itajackass, please when posting an issue do not delete the issue template.

Take a look at this tutorial for using picker in an HTML form: https://github.com/Simonwep/pickr/wiki/Using-Pickr-in-an-HTML-Form, and after following it, if you have the same results, please post a JSFiddle displaying the issue.

Have a great day!

**Comment by itajackass** [comment]
Hi @NateSeymour ,
I tried your link but example is not comprensive for me.
So I decided for now to continue using useAsButton = true to simplicity.

**Comment by Simonwep** [comment]
I think we're done here, if questions come up please comment :)
