### ISSUE TITLE
"appendToBody: true" is broken

### ISSUE THREAD

**Issue by yamass** [Simonwep/pickr#16]
#### Do you want to request a **feature** or report a **bug**? 
Bug.

#### What is the current behavior?
When setting "appendToBody: true", the popup does not open on click.

#### If the current behavior is a bug, please provide the steps to reproduce.
* Add `appendToBody: true,` to `gh-page/js/script.js`
* Open index.html
* Click on the example pickr.

#### What is the expected behavior?
Popup should open.

#### Your environment:
```
Pickr-version: master (166ce8d6671be16cf81b7cefa7e29c7b73738490)
Browser-version: 68.0.3440.42 (Official Build) beta (64-bit)
Operating-system:  MacOs
```

---

Pickr is great! Thank you so much!!

**Comment by Simonwep** [comment]
Thanks for awesome reporting! Very helpful :)

Oohps, didn't want to close it.

**Comment by yamass** [comment]
Seems to work now as of cca0cbc. 
Awesome! Thank you!!
