### ISSUE TITLE
How to use this library with a Vue project

### ISSUE THREAD

**Issue by bryan-ibrahim** [Simonwep/pickr#160]
#### Your environment:
```
Version (see Pickr.version):
Used bundle (es5 or normal one):
Used theme (default is classic): 
Browser-version:  
Operating-system:  
```

**Comment by bryan-ibrahim** [comment]
I've been trying to use this on a Vue project but I haven't been successful. I've done the initialization inside the mounted() life cycle method to load it when its ready but its not showing. Kindly help

` mounted() {
    console.log("Mounted!");
    const pickr = Pickr.create({
      el: ".pickr",
      theme: "classic", // or 'monolith', or 'nano'
      swatches: [
        "rgba(244, 67, 54, 1)",
        "rgba(233, 30, 99, 0.95)",
        "rgba(156, 39, 176, 0.9)",
        "rgba(103, 58, 183, 0.85)",
        "rgba(63, 81, 181, 0.8)",
        "rgba(33, 150, 243, 0.75)",
        "rgba(3, 169, 244, 0.7)",
        "rgba(0, 188, 212, 0.7)",
        "rgba(0, 150, 136, 0.75)",
        "rgba(76, 175, 80, 0.8)",
        "rgba(139, 195, 74, 0.85)",
        "rgba(205, 220, 57, 0.9)",
        "rgba(255, 235, 59, 0.95)",
        "rgba(255, 193, 7, 1)"
      ],
      components: {
        // Main components
        preview: true,
        opacity: true,
        hue: true,
        // Input / output Options
        interaction: {
          hex: true,
          rgba: true,
          hsla: true,
          hsva: true,
          cmyk: true,
          input: true,
          clear: true,
          save: true
        }
      }
    });
    console.log("Color picker object: ", pickr);
  },`

![color_pickr](https://user-images.githubusercontent.com/17259341/66177802-a2479480-e66b-11e9-9a92-b30eccdcf9e4.PNG)

**Comment by Simonwep** [comment]
@bryan-ibrahim I suggest using a vue-ref and passing the element directly as `el`, otherwise you'll run into issues if you want to spawn more than one.

**Comment by afiqiqmal** [comment]
using nuxtjs.. im using it like this..

`<template>
    <div :id="name" class="pickr"></div>
</template>

<script>
    export default {

	    name: "ColorInput",
        props: {
		    name: null,
            value: {
		        type: String,
                default: '#42445A'
            }
        },
        data() {
		    return {
		        picker: null,
                selectedColor: null,
                pickrOption: {
                    el: '#'+this.name,
                    default: this.value == null ? '#42445A' : this.value,
                    theme: 'nano',
                    swatches: [
                        'rgba(244, 67, 54, 1)',
                        'rgba(233, 30, 99, 0.95)',
                        'rgba(156, 39, 176, 0.9)',
                        'rgba(103, 58, 183, 0.85)',
                        'rgba(63, 81, 181, 0.8)',
                        'rgba(33, 150, 243, 0.75)',
                        'rgba(3, 169, 244, 0.7)',
                        'rgba(0, 188, 212, 0.7)',
                        'rgba(0, 150, 136, 0.75)',
                        'rgba(76, 175, 80, 0.8)',
                        'rgba(139, 195, 74, 0.85)',
                        'rgba(205, 220, 57, 0.9)',
                        'rgba(255, 235, 59, 0.95)',
                        'rgba(255, 193, 7, 1)'
                    ],

                    components: {
                        preview: true,
                        opacity: true,
                        hue: true,
                        interaction: {
                            input: true,
                            clear: true,
                            save: true
                        }
                    }
                }
            }
        },
        watch: {
	        value: function (a, b) {
                if (this.picker != null) {
                    this.picker.setColor(this.value, false);
                    this.picker.applyColor(false);
                }
            }
        },
        beforeDestroy() {
            if (this.picker != null) {
                this.picker.destroyAndRemove();
            }
        },
        mounted() {
            if (process.client) {
                if (this.name != null) {
                    this.pickrOption.el = '#' + this.name;
                    this.picker = Pickr.create(this.pickrOption);
                    this.picker.on('save', this.colorSave);
                    this.picker.on('change', this.colorChange);
                }
            }
        },
        methods: {
            colorChange(instance) {
                this.selectedColor = instance.toHEXA().toString();
            },
            colorSave(instance) {
                this.selectedColor = instance.toHEXA().toString();
                this.$emit('input', this.selectedColor);
                this.$emit('color-save', {
                    name: this.name,
                    color: this.selectedColor
                });
                this.picker.hide();
            }
        }
	}
</script>

<style lang="scss">
    .pickr {
        button {
            width: 40px !important;
            height: 40px !important;
        }
        position: absolute;
        top: 0;
        bottom: 0;
        left: 5px;
        display: flex;
        align-items: center;
    }
</style>
`

**Comment by afiqiqmal** [comment]
using nuxtjs.. im using it like this..

```
<template>
    <div :id="name" class="pickr"></div>
</template>

<script>
    export default {

        name: "ColorInput",
        props: {
            name: null,
            value: {
                type: String,
                default: '#42445A'
            }
        },
        data() {
            return {
                picker: null,
                selectedColor: null,
                pickrOption: {
                    el: '#'+this.name,
                    default: this.value == null ? '#42445A' : this.value,
                    theme: 'nano',
                    swatches: [
                        'rgba(244, 67, 54, 1)',
                        'rgba(233, 30, 99, 0.95)',
                        'rgba(156, 39, 176, 0.9)',
                        'rgba(103, 58, 183, 0.85)',
                        'rgba(63, 81, 181, 0.8)',
                        'rgba(33, 150, 243, 0.75)',
                        'rgba(3, 169, 244, 0.7)',
                        'rgba(0, 188, 212, 0.7)',
                        'rgba(0, 150, 136, 0.75)',
                        'rgba(76, 175, 80, 0.8)',
                        'rgba(139, 195, 74, 0.85)',
                        'rgba(205, 220, 57, 0.9)',
                        'rgba(255, 235, 59, 0.95)',
                        'rgba(255, 193, 7, 1)'
                    ],

                    components: {
                        preview: true,
                        opacity: true,
                        hue: true,
                        interaction: {
                            input: true,
                            clear: true,
                            save: true
                        }
                    }
                }
            }
        },
        watch: {
            value: function (a, b) {
                if (this.picker != null) {
                    this.picker.setColor(this.value, false);
                    this.picker.applyColor(false);
                }
            }
        },
        beforeDestroy() {
            if (this.picker != null) {
                this.picker.destroyAndRemove();
            }
        },
        mounted() {
            if (process.client) {
                if (this.name != null) {
                    this.pickrOption.el = '#' + this.name;
                    this.picker = Pickr.create(this.pickrOption);
                    this.picker.on('save', this.colorSave);
                    this.picker.on('change', this.colorChange);
                }
            }
        },
        methods: {
            colorChange(instance) {
                this.selectedColor = instance.toHEXA().toString();
            },
            colorSave(instance) {
                this.selectedColor = instance.toHEXA().toString();
                this.$emit('input', this.selectedColor);
                this.$emit('color-save', {
                    name: this.name,
                    color: this.selectedColor
                });
                this.picker.hide();
            }
        }
    }
</script>

<style lang="scss">
    .pickr {
        button {
            width: 40px !important;
            height: 40px !important;
        }
        position: absolute;
        top: 0;
        bottom: 0;
        left: 5px;
        display: flex;
        align-items: center;
    }
</style>

```

**Comment by joallard** [comment]
@Simonwep Just want to thank you for having taken the time to reply to this
