### ISSUE TITLE
plan to use multiple color picker

### ISSUE THREAD

**Issue by venkateshr8849** [Simonwep/pickr#161]
i wanna to add multiple color picker in my page.i need to know how to change color based on element instead of variable

ex:  $("#picker").colorpicker("setValue", "#ffffff");

**Comment by Simonwep** [comment]
Duplicate of #159, #127, #57 and #30

**Comment by venkateshr8849** [comment]
hey how can i set color in the element??

**Comment by Simonwep** [comment]
Checkout the [FAQ](https://github.com/Simonwep/pickr#faq). No it's not possible by classname (as already asked here like 5 times). Please search for existing issues which already cover your problem and leave comment there.
