### ISSUE TITLE
Typescript Typings : setColor

### ISSUE THREAD

**Issue by asharpefr** [Simonwep/pickr#164]
#### What is the current behavior?
Hi I think there is a little miss match in the typings, I cannot use setColor with a string in Typescript

In the documentation:
- pickr.setColor(representation:String, silent:Boolean):Boolean - Parses a string which represents a color (e.g. #fff, rgb(10, 156, 23)) or name e.g. 'magenta', returns true if the color has been accepted. null will clear the color.

In the pickr.d.ts file there is:
setColor(representation: Pickr.Representation, silent: boolean): boolean;

and Representation can only be 'HEXA' | 'RGBA' | 'HSVA' | 'HSLA' | 'CMYK'; 

Shouldn't it be : setColor(representation: string, silent: boolean): boolean; ?

#### Your environment:
```
Version (see Pickr.version): 1.4.4
```

**Comment by Simonwep** [comment]
It should be `setColor(str: string | null, silent: boolean)`. There's also a typo in the README... fixed in 59dbcf713c711763ff1d4f1ca9a462075b3d1da9 :)
