### ISSUE TITLE
[angular] Pick a color right after the picker instanciation

### ISSUE THREAD

**Issue by epitomz** [Simonwep/pickr#166]
#### Your environment:
```
Version (see Pickr.version): 1.4.5
Used bundle (es5 or normal one): es5 (for IE compatibility)
Used theme (default is classic): 
Browser-version:  Chrome
Operating-system:  Windows
```

Hi,

I have trouble to assign a value in a my picker wrapper of your component. As you can see in this [example](https://stackblitz.com/edit/angular-vk8h7d), I use an angular form to assign a color to a variable.

The `writeValue` method is called directly to do something with the variable value. I'm trying to use the `setColor()` method to apply the color. If you add a breakpoint right after you can see that the picker toggle changes to the good color but then it goes back to the default color.

Afterwards, anytime I pick a new color, the model is correctly binded as you can see in the example. (I'm assigning the new value whe the picker is hidden with `applyColor()` method

Could you give any advice here?

Thanks,
Antonin

**Comment by epitomz** [comment]
Ok, I finally manage to make it work by applying the received value during the `init`callback:

```
this.pickr.on('init', () => {
        this.pickr.setColor(this.color);
})
```

It shouldn't be necessary right?

**Comment by NateSeymour** [comment]
Hi Antonin,

This is exactly what you need to do :)

`Pickr` takes a little bit of time to load and initialize, and this is done asynchronously. This means that your code will most likely have already finished executing before `pickr` is ready to do anything useful. This is what the `init` event is for: it assures you that `pickr` is completely loaded and ready to be used.

Please let my know if you have any other questions.

Best regards,
Nathan
