### ISSUE TITLE
Pickr fires "onSave" during construction

### ISSUE THREAD

**Issue by yamass** [Simonwep/pickr#17]
#### Do you want to request a **feature** or report a **bug**? 
Bug (IMHO)

#### What is the current behavior?
Pickr fires the `onSave` event during construction.

#### If the current behavior is a bug, please provide the steps to reproduce.
Add to `gh-page/js/script.js` the following lines:
```
        onSave: function (hsva, instance) {
		console.log("onSave");
	}
```
Open index.html.

#### What is the expected behavior?
`onSave` should not be called (IMHO). It should only be called when the user makes a change.

#### Your environment:
```
Pickr-version: master (166ce8d6671be16cf81b7cefa7e29c7b73738490)
Browser-version:  68.0.3440.42 (Official Build) beta (64-bit)
Operating-system:  MacOs
```

**Comment by Simonwep** [comment]
Yeah, im not really sure if i **didn't** want to call this listener because it's basically a color-changing-action. 
For example, if you have a website where you want the ability to choose a custom background and you have a `onSave()` listener which set it. Then it would, IMO, helpful if it would be fired on initialization.

**Comment by yamass** [comment]
I totally understand your point. It is sometimes easier, if you _intentionally use_ this behavior in your application logic.

However, this kind of behavior might be non-expected for many developers, since none of the standard HTML inputs works like this. They only fire change events on user interaction, not on initialization, nor on API usage.

Also, if you do not rely on the onSave event being fired at initialization time, you may have to filter it out for performance reasons or for null-pointer prevention. That's what is happening in my case: 

```
// inside class constructor:
this.pickr = createPickr({
    ...
    onSave: (hsva, instance) => {
	if (this.pickr != null) { // pickr is currently initializing, I cannot use it (nullpointer exceptions)
            this.methodUsingPickr(); // do something using this.pickr (not instance!)
        }
    },
});
```

**Comment by yamass** [comment]
Looks good. I will test it on Monday. Thank you!!
