### ISSUE TITLE
Swatches with description and custom layout

### ISSUE THREAD

**Issue by DevelGitH** [Simonwep/pickr#170]
In my use case I have to set for each swatches color a own description. To be dynamic it would be an advantage to write also a custom html template for the swatches palette.

Possible implementation: 

```
Pickr.create({
    swatches: [
        {
            "color": "#f44336",
            //dynamic_properties like description e.g.....
        },
        {
            "color": "#fff",
            //dynamic_properties like description e.g.....
        }
    ],
    swatchesTemplate: `
        // use handlebars or another parser
    `
});
```
Within the property swatchesTemplate the default template can be overriden with the defined template, where the developer should have full access to the declared properties in the pickr instance.

**Comment by Simonwep** [comment]
Well I can't an will not implement / use an **extra** parser just for the template. I may implement a very, very small one by myself in the future see #44 for more info and news! :)

Subscribe to the thread above to stay up-to-date to news about custom-templates etc!
