### ISSUE TITLE
Feature suggestion: make it possible that the color picker can be zoomed in and out

### ISSUE THREAD

**Issue by melvinroest** [Simonwep/pickr#171]
**Is your feature request related to a problem? Please describe.**
I wanted the color picker to work when zoomed in (like 5 times). The issue with that is that I had to scale the color picker, making it smaller. This caused an issue, since the components are build at startup and `getBoundingClientRect` does not change dynamically.

**Describe the solution you'd like**
I want the color picker to function when you zoom in. I'm using a very minimal version of your color picker, so I hacked the following code together (but it might be broken with some other things that I don't use):

```
if (inst._recalc) {
  const zoom = document.documentElement.clientWidth / window.innerWidth;
  x = x * zoom;
  y = y * zoom;

  // Calculate saturation based on the position
  color.s = x * 100;

  // Calculate the value
  color.v = 100 - y * 100;
```
```
// Calculate hue
const zoom = document.documentElement.clientWidth / window.innerWidth;
if (inst._recalc) {
  color.h = v * zoom * 360;
}
```

```
const zoom = document.documentElement.clientWidth / window.innerWidth;
if (inst._recalc) {
  color.a = Math.round(v * zoom * 1e2) / 100;
}
```

**Describe alternatives you've considered**
I didn't consider any alternatives.

**Additional context**
I'm happy with my hack, but I just wanted to give you this as an idea.

**Comment by Simonwep** [comment]
Sorry, what do you mean if zoomed in? On both mobile and desktop it still works.
Do you mean the general layout (which could be changed with custom-css)?

**Comment by melvinroest** [comment]
Here is what I mean. The following gif is recorded on an ipad. When I zoom in, you get to see the color picker, because my hack is in place (see code above). If my hack wasn't in place, then I could not display my gif.

What you see is that the menu is constantly scaled down to the viewport. This means that I needed to scale down the color picker as well. When that happens, bugs started to appear.

Here's the video of it working (note: it wouldn't work without my applied hacky patch).


![ezgif com-optimize](https://user-images.githubusercontent.com/44729293/67699590-a9349f00-f9ac-11e9-96c2-a0013f5725a4.gif)

**Comment by NateSeymour** [comment]
Closed due to inactivity.
