### ISSUE TITLE
ES5 bundle breaks in IE11 due to Array.prototype.includes()

### ISSUE THREAD

**Issue by chief-jai** [Simonwep/pickr#174]
I have problems with using the ES5 bundle in IE11. It still uses Array.prototype.inclues() method which is not supported in IE.

Pickr Version: 1.4.5

Is there a way I could work around this?

**Comment by Simonwep** [comment]
Checkout #173 We're working on a "official" IE11 compatible version!

**Comment by Simonwep** [comment]
I've merged the PR. Please take a look at the note about the es5-bundle below [node](https://github.com/Simonwep/pickr#node) in the README!
