### ISSUE TITLE
onChange event gives old color value when calling setColor()

### ISSUE THREAD

**Issue by chuen1118** [Simonwep/pickr#176]
#### What is the current behavior?
Calling `setColor(newColor)` fired change event, however the change event callback
```
pickr.on('change', (color, instance) => {
    console.log('change', color, instance);
})
```
provided the old color instead of the one I passed to `setColor()`.

#### Please provide the steps to reproduce and create a [JSFiddle](https://jsfiddle.net/Simonwep/qx2Lod6r/).

 [Demo](https://jsfiddle.net/nehuc11/w4tey2vr/)

#### What is the expected behavior?
The new color is expected.

#### Your environment:
```
Version (see Pickr.version): 1.4.6
Used bundle (es5 or normal one): normal
Used theme (default is classic): monolith
Browser-version:  
Operating-system:  
```

**Comment by Simonwep** [comment]
Fixed in d090baf :)
