### ISSUE TITLE
Error when release the mouse outside the selection while dragging the color selection

### ISSUE THREAD

**Issue by nbenvn** [Simonwep/pickr#177]
![image](https://user-images.githubusercontent.com/8096313/68443346-34603100-0206-11ea-8741-cfb6c3ef96c7.png)

This action will trigger an error when moving the mouse over the page

![ag](https://user-images.githubusercontent.com/8096313/68443827-abe29000-0207-11ea-89a7-35fa44716c89.gif)

**Comment by Simonwep** [comment]
I can't reproduce it, could you provide a JSFiddle?

**Comment by nbenvn** [comment]
Sorry, this is my fault. Another event destroyed Pickr before the hidden popup.
