### ISSUE TITLE
Initiating empty Color Picker without interactions causes issue with the `focus-border`

### ISSUE THREAD

**Issue by shilo-ey** [Simonwep/pickr#179]
#### What is the current behavior?
When initiating the Color Picker without a default color and without color conversion interactions (e.g `hex`, `rgba` etc...), the following unwanted behavior occurs:
![image](https://user-images.githubusercontent.com/45009641/68837775-fbbccd80-06c5-11ea-8a34-be20e4978d9b.png)

The opacity and hue slider handles are unselected (without a fill)

#### Please provide the steps to reproduce and create a [JSFiddle](https://jsfiddle.net/Simonwep/qx2Lod6r/).

https://jsfiddle.net/4tvadnqp/
Bug reproduces in this link ^

#### What is the expected behavior?
The picker `focus-border` on the `pickr-circles` should be selected/over the color bars and not beneath them.

Thanks!

**Comment by Simonwep** [comment]
Sorry, I think I don't get it. I thought you wanted focus-border on these little knobs to adjust values?

**Comment by NateSeymour** [comment]
See https://github.com/Simonwep/pickr/issues/178#issuecomment-555023160
