### ISSUE TITLE
Can't select #000000 in "nano" mode.

### ISSUE THREAD

**Issue by ap-technologies** [Simonwep/pickr#180]
I can't select #000000 in "nano" mode when I click the bottom-left corner.

**Comment by NateSeymour** [comment]
Please don't delete the issue template.

Recreate this issue with a fiddle and more information please, so that I am able to help you. Thank you.

**Comment by Simonwep** [comment]
@ap-technologies At least on the demo it seems to work fine. I don't know what you mean by "select" in this case though
