### ISSUE TITLE
HSVaColor methods toString()

### ISSUE THREAD

**Issue by bsastregx** [Simonwep/pickr#182]
According to the documentation, toString() method on the **HSVaColor object** toRGBA() method, can receive a number to round the decimal value : https://github.com/Simonwep/pickr#the-hsvacolor-object

However, this is not the case. We are trying to pass 0, in order to return the value without any decimal values, and we get : "Expected 0 arguments, but got 1."

Looking at the implementation, it doesn't provide the redefinition of the toString method : 

```
    interface HSVaColor {
        toHSVA(): Array<number>,

        toHSLA(): Array<number>,

        toRGBA(): Array<number>,

        toCMYK(): Array<number>,

        toHEXA(): Array<number>,

        clone(): HSVaColor
    }

```

**Comment by Simonwep** [comment]
Actually the toString function of `Array<number>` is overridden. But you're right, I've updated it here: https://github.com/Simonwep/pickr/commit/3a6181fed3cc9c0423a8ebd76bde58ca1e7bd891#diff-573ce24aa615d6a8c9a110355faf562bR101!
