### ISSUE TITLE
RePositioningPicker null check

### ISSUE THREAD

**Issue by ms007** [Simonwep/pickr#183]
Hi 
Thank you for investing your time to create such a great library. 

It almost works for me with react. 

The first time the picker is rendered (on subsequent renderings it works) I get an uncaught type error on _rePositioningPicker because options is null at this time. 

https://s.put.re/ivXz5VkV.png

could you just add a null check of options before accessing it?
it would solve my scenario

thank you a lot

**Comment by Simonwep** [comment]
Hey :) Thank you for using it!

Unfortunately options are required to be defined to initialize pickr. Did you tried putting the initialization into [componentDidMount](https://reactjs.org/docs/react-component.html#componentdidmount)? 

If you encounter and pickr-related issues a JSFiddle would help! (please don't remove the issue template the next time or it'll be closed immediatly.)

**Comment by Simonwep** [comment]
Closed due inactivity.
