### ISSUE TITLE
Select input on show

### ISSUE THREAD

**Issue by nevilleomangi** [Simonwep/pickr#184]
**Is your feature request related to a problem? Please describe.**
It is not possible to select or focus input.pcr-result on 'show'. 
I went through the code, I noticed the selection is disabled on launch [I suppose in order to prevent mouse scrolls altering the value before someone clicks inside the input?]

**Describe the solution you'd like**
Add the option to select/focus the result input on 'show'

**Describe alternatives you've considered**
N/A

**Additional context**
My use case: I need to enable a user of my app to quickly add a new color by pasting the contents of the clipboard.
I noticed I am not able to attach an event listener in order to use 'Enter' key to save. Possibly related.

**Comment by Simonwep** [comment]
[Here you go](https://jsfiddle.net/Simonwep/exzyoufp/). The browser needs to to two repaints (Recalculating position and updating HTML Properties if I remember correctly).

**Comment by nevilleomangi** [comment]
That fixes it. Thanks!
