### ISSUE TITLE
Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by DamjanRI** [Simonwep/pickr#185]
Having problem with pickr issue  "Right-hand side of 'instanceof' is not callable" in utils.js ( if (elements instanceof HTMLCollection || elements instanceof NodeList))
I have created following function to call pickr, on one page it works, on another it creates issue, here is my function

function pickColor(e, styleElement, value, onFineChange) {
    if (styleElement != '') value = $("#" + styleElement).css('background-color');
    const pickr = new Pickr(Object.assign({
        el: e,
        theme: 'classic',
        container: 'body',
        useAsButton: true,
        default: value,
        swatches: [
            'rgba(244, 67, 54, 1)',
            'rgba(233, 30, 99, 0.95)',
            'rgba(156, 39, 176, 0.9)',
            'rgba(103, 58, 183, 0.85)',
            'rgba(63, 81, 181, 0.8)',
            'rgba(33, 150, 243, 0.75)',
            'rgba(3, 169, 244, 0.7)',
            'rgba(0, 188, 212, 0.7)',
            'rgba(0, 150, 136, 0.75)',
            'rgba(76, 175, 80, 0.8)',
            'rgba(139, 195, 74, 0.85)',
            'rgba(205, 220, 57, 0.9)',
            'rgba(255, 235, 59, 0.95)',
            'rgba(255, 193, 7, 1)'
        ],

        components: {

            // Main components
            preview: true,
            opacity: true,
            hue: true,

            // Input / output Options
            interaction: {
                hex: true,
                rgba: true,
                hsla: true,
                hsva: true,
                cmyk: true,
                input: true,
                clear: false,
                save: false
            }
        }
    }));

    pickr.on('change', (color, instance) => {
        $("#" + styleElement).css('background-color', color.toRGBA().toString());
        onFineChange(color.toRGBA().toString());
    })

    pickr.show();
}

**Comment by Simonwep** [comment]
Please stick to the [Issue Template](https://github.com/Simonwep/pickr/blob/master/.github/ISSUE_TEMPLATE.md). Create a JSFiddle and describe what you've done as detailed as possible and break your issue down to a minimum. This will help me to resolve it as fast as possible.
