### ISSUE TITLE
color.toRGBA is not a function

### ISSUE THREAD

**Issue by bdb400** [Simonwep/pickr#188]
![image](https://user-images.githubusercontent.com/5695811/71812380-473f8800-3034-11ea-8cf8-ee323e69f064.png)

**Comment by Simonwep** [comment]
Let me guess... `color` is undefined? :D

**Comment by bdb400** [comment]
![image](https://user-images.githubusercontent.com/5695811/71826000-30139100-305a-11ea-9b05-40ebb4b3c81f.png)

**Comment by bdb400** [comment]
What do I do to fix it?

**Comment by Simonwep** [comment]
The first thing which would be cool if you'd provide a fiddle with the actual problem.
You have no variable in the scope named `color` - so how should that work? You copied your code from your `save` listener in init, but didn't even bothered a) looking at the docs and b) checking whenever there's a `color` argument available in the init.
