### ISSUE TITLE
parseToHSV() does not handle "1" alpha values

### ISSUE THREAD

**Issue by yamass** [Simonwep/pickr#19]
#### Do you want to request a **feature** or report a **bug**? 
Bug.

#### What is the current behavior?
`Color.parseToHSV("rgba(70,70,70,1)")` returns null.

#### If the current behavior is a bug, please provide the steps to reproduce.
Color.parseToHSV("rgba(70,70,70,1)")

#### What is the expected behavior?
return the correct value.
This seems to be a regression introduced by 166ce8d6671be16cf81b7cefa7e29c7b73738490

#### Your environment:
```
Pickr-version: latest master
Browser-version:  Chrome 68 beta
Operating-system:  MacOs
```

**Comment by Simonwep** [comment]
Damn, I dont wanna close it by myself haha... anyway, I've fixed it!

**Comment by yamass** [comment]
Thanks!
