### ISSUE TITLE
It's not working properly with multiple instance

### ISSUE THREAD

**Issue by AinCoder** [Simonwep/pickr#194]
![image](https://user-images.githubusercontent.com/26634947/76171048-99766400-61b1-11ea-9e8d-7b4583fa4031.png)

Can you tell me why it's not catching the event?
The color select part is working.

Or is there any way to use it with multiple inputs in a same page?

Here is my full code

        $Picker = [];
        $('.pickr').each(function () {
            $this = $(this);
            $ID = "picker" + Math.round(Math.random() * 10);
            $Picker.push($ID);
            $this.attr('id',$ID);
            new Pickr({
                el: '#'+$ID,
                useAsButton: true,
                default: '#42445A',
                theme: 'nano',
                swatches: [
                    'rgba(244, 67, 54, 1)',
                    'rgba(233, 30, 99, 0.95)',
                    'rgba(156, 39, 176, 0.9)',
                    'rgba(103, 58, 183, 0.85)',
                    'rgba(63, 81, 181, 0.8)',
                    'rgba(33, 150, 243, 0.75)',
                    'rgba(3, 169, 244, 0.7)',
                    'rgba(0, 188, 212, 0.7)',
                    'rgba(0, 150, 136, 0.75)',
                    'rgba(76, 175, 80, 0.8)',
                    'rgba(139, 195, 74, 0.85)',
                    'rgba(205, 220, 57, 0.9)',
                    'rgba(255, 235, 59, 0.95)',
                    'rgba(255, 193, 7, 1)'
                ],
                components: {
                    preview: true,
                    opacity: true,
                    hue: true,
                    interaction: {
                        hex: true,
                        rgba: true,
                        input: true,
                        save: true,
                        clear: true
                    }
                }
            });
            $this.on('focus click',function () {
                console.log('clicked');
            })
        });
        $Picker.forEach(function (index) {
            console.log(index);
            Pickr.on('#'+index,'init',function (P) {
                console.log('TTTTT',P.getSelectedColor().toRGBA().toString(0))
            });

        });

**Comment by Simonwep** [comment]
Please stick to the [Issue Template](https://github.com/Simonwep/pickr/blob/master/.github/ISSUE_TEMPLATE.md). Create a JSFiddle and describe what you've done as detailed as possible and break your issue down to a minimum. This will help me to resolve it as fast as possible.

**Comment by AinCoder** [comment]
Thanks a lot, @Simonwep for your quick reply!
I just fixed my issue and now I'm able to use it on multiple inputs on the same page.
