### ISSUE TITLE
[Browser] Can't import typings in tsconfig.json

### ISSUE THREAD

**Issue by DarkMatterMatt** [Simonwep/pickr#199]
Just thought I'd start by saying this is an amazing library - it looks great and just works!

#### What is the current behavior?
I am using Pickr through a script tag for `cdn.jsdelivr.net` and I can't import typings using the following `tsconfig.json`:

    {
        "compilerOptions": {
            "typeRoots": [ "./node_modules/@simonwep" ],
            "types": [ "pickr" ]
        }
    }

I can import typings for my browser-based project by doing `import Pickr from "@simonwep/pickr"`. This compiles into `require("@simonwep/pickr")` in the final JS which I don't want, as I am not running Node.
I can import typings if I remove the last line of `types/pickr.d.ts`, which is `export default Pickr;`

#### What is the expected behavior?
I should (I think?) be able to use the typings in a browser-based project, by using the `tsconfig.json` above.

#### Your environment:
```
Version (see Pickr.version): https://cdn.jsdelivr.net/npm/@simonwep/pickr/dist/pickr.min.js
Used bundle (es5 or normal one): normal
Used theme (default is classic): N/A (but I love monolith :D)
Browser-version:  N/A (Chrome)
Operating-system:  Windows 10
```

Apologies if I've used incorrect terminology as I'm very new to typescript (is there a better way to include typings?). Let me know if I can clarify anything 😄

**Comment by Simonwep** [comment]
Hi, thanks! You're welcome :)

There's no need to tell TS where types for pickr can be found, they're referenced over the [typings field](https://github.com/Simonwep/pickr/blob/master/package.json#L13) inside of `package.json`. 

The CDN-Version (over jsdelivr) is normally meant to be used if you're _not_ using any bundler (and therefore no typescript or other js-supersets). If you still want to do that you need to use the very same version of pickr in both your `package.json` _and_ your HTML file...

So _instead_ I'd recommend taking a look at [webpack](https://webpack.js.org/) and the corresponding [ts-loader](https://github.com/TypeStrong/ts-loader) for typescript. I never used the stand-alone `tsc` compiler for such things and I think bundling stuff for the browser is not supported by it  :/

**Comment by DarkMatterMatt** [comment]
That's a good point about needing to sync the versions across the HTML file and in my `package.json`.
I'll look into webpack, thanks for your help :)

**Comment by Simonwep** [comment]
You're welcome :) [Traversy Media](https://www.youtube.com/results?search_query=traversy+media+webpack) and especially [The Net Ninja](https://www.youtube.com/results?search_query=the+net+ninja+webpack) are very, very good places to start as Webpack may seem very confusing at the beginning.
