### ISSUE TITLE
The color keep changing even when I'm not clicking anymore

### ISSUE THREAD

**Issue by stat1k** [Simonwep/pickr#203]
#### What is the current behavior?
When I click in the color picker area or in the settings on the right, the circle keep following my cursor and changing the color even though I'm not clicking on it anymore.
#### What is the expected behavior?
When I mouseup, the color need to be locked.
#### Your environment:
```
Version (see Pickr.version): 1.5.1
Used bundle (es5 or normal one): normal
Used theme (default is classic): classic
Browser-version:  Chrome 80
Operating-system:  macOS Mojave but the problem is also in Ubuntu
JS Framework: Angular 2.4.10
```

![problem_pickr](https://user-images.githubusercontent.com/3199782/78987171-88f93680-7b2d-11ea-9742-9a0a56227749.gif)

It's a shame because the plugin is awesome !
Thanks you for your time :)

**Comment by Simonwep** [comment]
Hi!
Could you reproduce the issue with [JSFiddle]((https://jsfiddle.net/Simonwep/qx2Lod6r/))? 
The handler to detect whenever you finished your selection [gets immediately](https://github.com/Simonwep/pickr/blob/master/src/js/libs/moveable.js#L54) attached to the document after you started. 
You could check if there's any event-handler attached to `document` which calls `stopPropagation` / `stopImmediatePropagation`.

**Comment by stat1k** [comment]
Hello,
Thanks a lot for the fast response, unfortunately I couldn't reproduce the issue on JSFiddle.
I try to look where the problem must be and I find that Zone.js (a require package on Angular 2) keep adding the "mousemove" Event Listeners on my document.
I try to fix it but I didn't succeed, so sadly I think I will use and another plugin :(
Thanks again for your time and this amazing plugin !

**Comment by nithilan4** [comment]
i had the same issue and it was caused by having a duplicate changestop event handler

**Comment by Simonwep** [comment]
Closing because it's domain specific and inactive.
