### ISSUE TITLE
t.el is null on line 187

### ISSUE THREAD

**Issue by Noah-Franks** [Simonwep/pickr#204]
t.el is null on line 187 in the minified file

#### Your environment:
```
Version (see Pickr.version): 1.5.1
Used bundle (es5 or normal one): both
Used theme (default is classic):  nano
Browser-version:  Firefox 75.0 (64-bit)
Operating-system:  Ubuntu 18.04
```

**Comment by Simonwep** [comment]
Please stick to the [Issue Template](https://github.com/Simonwep/pickr/blob/master/.github/ISSUE_TEMPLATE.md). Create a JSFiddle and describe what you've done as detailed as possible and break your issue down to a minimum. This will help me to resolve it as fast as possible.
