### ISSUE TITLE
How can I change options when pickr is created

### ISSUE THREAD

**Issue by cydiacen** [Simonwep/pickr#208]
#### Your environment:
```
Version (see Pickr.version):1.5.1
Used bundle (es5 or normal one):es6
Used theme (default is classic): classic
Browser-version:  
Operating-system:  
```
I want to change strings to support i18n when pickr is created.
but i can not find some methods to use.
has any solution?

**Comment by Simonwep** [comment]
This is only possible in the upcoming [i18n feature](https://github.com/Simonwep/pickr/tree/i18n), I will release a new version in the coming days as there are several issues related to it.

**Comment by cydiacen** [comment]
thx for your reply
Looking forward to your update
