### ISSUE TITLE
Cannot have two event listeners at the same time

### ISSUE THREAD

**Issue by kibebr** [Simonwep/pickr#209]
#### What is the current behavior?
When trying to use two event listeners, the second event listener will run the first event listener's call back function somehow

#### Please provide the steps to reproduce and create a [JSFiddle]
Here is the [JSFiddle](https://jsfiddle.net/o4vb3rds/5/)

Steps to reproduce:
1. Create two event listeners, in this case for `clear` and `save`
2. Manipulate `save`'s `color` callback variable
3. Now whatever you do inside `clear`'s event listener will cause an error, example:
`Uncaught TypeError: Cannot read property 'toHEXA' of null`

#### What is the expected behavior?
I am not really sure what is happening but it seems like the two event listeners are dependent on each other. Even if they are unrelated, the second event listener `clear` tries to access `save`'s `color` variable.

#### Your environment:
```
Version (see Pickr.version): 1.6.0
Used bundle (es5 or normal one): Normal
Used theme (default is classic): Nano
Browser-version:  Google Chrome | 81.0.4044.113 (Official Build) (64-bit)
Operating-system:  Linux
```

I am not that experienced and am not sure if this is indeed a bug; either way, thank you so much for this library!

**Comment by Simonwep** [comment]
Hey :)
As stated in [Events](https://github.com/Simonwep/pickr#events) `save` will be called with `null` as `color` since, well, you chose "no color".

**Comment by kibebr** [comment]
@Simonwep 
Oops, that was my bad! Didn't know `clear` fired `save` as well. Thank you so much.
