### ISSUE TITLE
Opening page on <iframe> prevents color picker modal to show on mobile devices

### ISSUE THREAD

**Issue by MatiasFMolinari** [Simonwep/pickr#21]
#### Steps to reproduce

1. Setup a page on a test website that opens the Pickr homepage on an iframe. (I'm using a route on a Ruby on Rails site.)
2. Open the page on a mobile device browser.
3. Click on the Pickr button. (Expected: The color picker modal should pop up, but it does not).

#### Example reproduction

This url opens Pickr's homepage on an iframe:

https://pacific-temple-66916.herokuapp.com/test-color-picker <- No longer available

In my case, it works on Desktop browsers, but not on mobile versions (iOS) of Chrome, Safari & Firefox.

#### Test variations and other comments

- I tested it with appendToBody as well with the same results.
- I noticed that the class containing the visibility trigger is added when I tap the button, so that seems to be working (Although the web inspector was highlighting it on and off as if it was being added then removed then added again, idk). I wanted to keep testing but my mobile web inspector kept crashing for some reason so I could not test it any further.
- Could this have something to do with my own Rails app's CSP? I might try a different framework later to see if this also occurs.

#### Environment
```
Pickr-version: master
Browser-version:
  - iOS Google Chrome (Version: 67.0.3396.87)
  - iOS Safari (Version: Latest?)
  - iOS Firefox (Version: 12.1)
Operating-system: iOS 11.4 (iPhone 7 Plus)
```

Thanks in advance for this awesome tool! Definitely excited to see where it goes.

**Comment by Simonwep** [comment]
Thanks for this awesome issue report, very clean :)

Uhmm, that's strange... I've opened your demo-url on my phone and tablet, both `Android 7.0`, with `Firefox 60.0.2` and `Chrome 67.0.3396.87` and everything works fine. Either it has a general problem with iOS devices, or I missing something.

I will do some investigation in the next day's! Unfortunately I didn't have any apple-device.

**Comment by MatiasFMolinari** [comment]
Thank you! I'll let you know if I figure something out.

**Comment by MatiasFMolinari** [comment]
I think I found the culprit:
https://stackoverflow.com/questions/7548833/ios-css-opacity-visibility-transition

Potential solutions:
1. https://stackoverflow.com/questions/7548833/ios-css-opacity-visibility-transition#comment44980835_10702958
2. https://stackoverflow.com/questions/7548833/ios-css-opacity-visibility-transition#comment44980835_10702958

**Comment by Simonwep** [comment]
Perfect! The second one looks like a good solution, could you override this style and try it:

```css
.pcr-app {
    transition: opacity 0.3s !important;
}
```

would be awesome 'cause I cannot test it. If this works I will fix it in the master branch :)

**Comment by MatiasFMolinari** [comment]
Yes, that works perfectly. I've tested it in a couple of mobile browsers on iOS. If you haven't used up your free trails, you could try a physical device testing products like browserstack.com to be sure.
