### ISSUE TITLE
Changing the color box button's width and height programmatically.

### ISSUE THREAD

**Issue by yesilcimenahmet** [Simonwep/pickr#211]
Hi,

The available color box sizes are high and I don't want to change this through the CSS file. Maybe you can offer an option. For example, it can be 16x16, 24x24, 32x32 and 64x64.

Can you add this feature?

Thanks.

**Comment by Simonwep** [comment]
No, there are already way enough options and doing this just for one of thousand use-cases is not reasonable. It's literally just 4 lines of css and the classes (such as `pcr-button` which is used for the button) are not mangled - therefore it's easy to style pickr as you want.

Adding such features implies adding options for all other elements in case someone wants to change _anything_ with js - that just doesn't work out.

There has to be a balance between available options given by a library and ease-of-access changing stuff, which is in this case quite easy as I already mentioned.

And if you want to do it programmatically, you can always use `classList.add` or `.style` on the button element which can get, among all other elements, accessed by `pickr.getRoot()` (See [methods](https://github.com/Simonwep/pickr#methods)).
