### ISSUE TITLE
Use pickr with NuxtJS

### ISSUE THREAD

**Issue by tsangaris** [Simonwep/pickr#212]
I was wondering how can i make this work with NuxtJS.

What I did so far:

1. Created a file in `plugins/pickr.js`
2. Inside this JS file I added 
`import Vue from 'vue'`
`import Pickr from '@simonwep/pickr'`
`Vue.use(Pickr)`
3. Inside nuxt.config.js inside **plugins** I added:
`'~/plugins/pickr'`
4. Inside nuxt.config.js inside build I added:
`transpile: ['pickr']`

After trying to use Pickr in one of my .vue files I get errors although server and client are compiled successfully.

Any ideas what is going wrong and how i can solve this?

Thank you in advance.

#### Your environment:
```
Version (see Pickr.version): "@simonwep/pickr": "^1.6.0",
Used bundle (es5 or normal one): used npm to bring it in
Used theme (default is classic):  classic
Browser-version:  latest Chrome
Operating-system:  latest MacOS
```

**Comment by ifarobi** [comment]
It works for me when I try to add cdn script and css on head method instead of using plugins or import the module. Already tried to using modules and plugins but got errors, but this might work 👀
```
...
head() {
    return {
      link: [
        {
          rel: 'stylesheet',
          href:
            'https://cdn.jsdelivr.net/npm/@simonwep/pickr/dist/themes/nano.min.css'
        }
      ],
      script: [
        {
          src: 'https://cdn.jsdelivr.net/npm/@simonwep/pickr/dist/pickr.min.js'
        }
      ]
    }
  }
...
```
then call `Pickr` object using `window.Pickr`

**Comment by tsangaris** [comment]
> It works for me when I try to add cdn script and css on head method instead of using plugins or import the module. Already tried to using modules and plugins but got errors, but this might work 👀
> 
> ```
> 
> ...
> 
>   head() {
> 
>     return {
> 
>       link: [
> 
>         {
> 
>           rel: 'stylesheet',
> 
>           href:
> 
>             'https://cdn.jsdelivr.net/npm/@simonwep/pickr/dist/themes/nano.min.css'
> 
>         }
> 
>       ],
> 
>       script: [
> 
>         {
> 
>           src: 'https://cdn.jsdelivr.net/npm/@simonwep/pickr/dist/pickr.min.js'
> 
>         }
> 
>       ]
> 
>     }
> 
>   }
> 
> ...
> 
> ```
> 
> then call `Pickr` object using `window.Pickr`

I havent tried that but it could be a solution! Although it would be great to have it working with import as well!

**Comment by Simonwep** [comment]
`'@simonwep/pickr'` is not a Vue plugin, vue is mentioned literally nowhere. Use vue refs and mount it manually.

**Comment by stefa168** [comment]
> 
> 
> `'@simonwep/pickr'` is not a Vue plugin, vue is mentioned literally nowhere. Use vue refs and mount it manually.

Sorry to ask, but do you have an example on how to use a ref with pickr? I am learning vue templates and I have tried myself to use a ref, however I'm not getting good results

**Comment by Flowko** [comment]
damn, this way late, but for anyone else who needs help with it:
```js
const selectedColor = ref("#B30A0A");

onMounted(() => {
  const pickr = window.Pickr.create({
    el: ".colorpicker",
    theme: "monolith",
    default: selectedColor.value,
    swatches: [
      "rgba(244, 67, 54, 1)",
      "rgba(233, 30, 99, 0.95)",
      "rgba(156, 39, 176, 0.9)",
      "rgba(103, 58, 183, 0.85)",
      "rgba(63, 81, 181, 0.8)",
      "rgba(33, 150, 243, 0.75)",
      "rgba(3, 169, 244, 0.7)",
    ],
    defaultRepresentation: "HEXA",
    components: {
      // Main components
      preview: true,
      opacity: true,
      hue: true,
      // Input / output Options
      interaction: {
        hex: false,
        rgba: false,
        hsva: false,
        input: true,
        clear: true,
        save: true,
      },
    },
  });

  pickr.on("save", (color, instance) => {
    instance.hide();
    selectedColor.value = color.toHEXA().toString();
  });
});
```
