### ISSUE TITLE
Some bug on your demo page, probably not there only

### ISSUE THREAD

**Issue by Evangeline-Rei** [Simonwep/pickr#213]
Here is some issue on slider direction on your demo page.

https://simonwep.github.io/pickr/

If I switch bookmark to monolith or nano, then back to classic, slider direction always horizontal, but should be vertical in classic mode.
Chromium 83.0.478.37
FF 76.0.1

**Comment by Simonwep** [comment]
Whups that's a bug in 26539fdb42a4ee0aeb6927fb230d747e23fda9c7...
Fixed in 8f8e7a5d3e97ced925cf6261e740c7ac113d6e8f, there's no release between the regression and bug fix so everything should be fine, thanks for reporting it :)
