### ISSUE TITLE
Can the function of displaying historical color selection be added？

### ISSUE THREAD

**Issue by cangshudada** [Simonwep/pickr#215]
**Is your feature request related to a problem? Please describe.**
I want to know what colors I have chosen recently, and I can choose them

**Describe the solution you'd like**
Add a historical selected color bar to display the 6 to 8 colors recently selected

**Additional context**
just like this
![1591248350(1)](https://user-images.githubusercontent.com/40785860/83718102-f2e21800-a666-11ea-922d-e20b139a985f.jpg)

**Comment by Simonwep** [comment]
You can use the swatches feature. Listen for the `save` event and add a swatch with the given color every time. If you reached 10 swatches you could remove the latest one with `removeSwatch` to rotate.

**Comment by cangshudada** [comment]
> You can use the swatches feature. Listen for the `save` event and add a swatch with the given color every time. If you reached 10 swatches you could remove the latest one with `removeSwatch` to rotate.

sounds great, thanks for your reply😉
