### ISSUE TITLE
Blazor issue

### ISSUE THREAD

**Issue by shaden187** [Simonwep/pickr#224]
Hello,
i want to check if this color picker is compatible with blazor ?
i followed all the required steps but it didnt work .
the only way to let it work is to remove the line:
<script src="_framework/blazor.server.js"></script> in _Host.cshtml file, but this line is important to use other blazor features.

**Comment by Simonwep** [comment]
Please stick to the [Issue Template](https://github.com/Simonwep/pickr/blob/master/.github/ISSUE_TEMPLATE.md). Create a JSFiddle and describe what you've done as detailed as possible and break your issue down to a minimum. This will help me to resolve it as fast as possible.
