### ISSUE TITLE
Swatch segmentation

### ISSUE THREAD

**Issue by DavidWikstrom** [Simonwep/pickr#230]
First of all, I'm just getting started with pickr, so apologies if the below already exists but I've simply not been able to figure out how to do it...

I'm working on an implementation where the users need to be able to pick from different sets of colors. The first segment will e.g. be bright colors, the second grayscale and the third a paler palette. Currently, filling the swatch with these colors just lines them up one after another in a way that doesn't allow the users to easily see and choose from the different segments. For now, I've added white swatches to fill out the rows as a workaround.

I would like to see an option to either add more than one swatch to each picker, or else, have a "segment" attribute for each color in the swatch (whatever works best).
Each segment or sub-swatch would then wrap so that the next segment always starts on a new line.

Another option could possibly be a feature that would allow for inserting a "hard line break" between swatches.

<img width="515" alt="Screen Shot 2020-07-10 at 13 45 15" src="https://user-images.githubusercontent.com/13996332/87151710-a1a3f480-c2b4-11ea-8ef0-52e115a74e15.png">

**Comment by Simonwep** [comment]
Hey :) This is a really good Idea, probably related to #44 - Right now this is not possible, you might find a work-around using [CSS Grid](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) and custom styling (used css-classes are not mangled and open to customization).

**Comment by DavidWikstrom** [comment]
Thanks! I'll probably stick with my workaround for now, but if I need something fancier, modifying template.js does sounds like a good option.
