### ISSUE TITLE
Setting picker button to be a custom icon?

### ISSUE THREAD

**Issue by EdwardDeaver** [Simonwep/pickr#237]
#### Your question
Is it possible to set the picker button to be an SVG icon instead of a normal button? 

#### Your environment:
```
Version: v1.7.2
Used bundle normal
Used theme default
Browser-version:  Chrome
Operating-system:  Windows
```

**Comment by Simonwep** [comment]
Checkout the `useAsButton` option, it lets you use whatever element you want as button :)

**Comment by EdwardDeaver** [comment]
Thank you so much! 

Also, thank you for this library it's really awesome. I love the built in action events, and when I was doing some mobile testing in chrome's emulator it was one of the very few that allowed touch screen users to just slide their finger on the gradients color view.
