### ISSUE TITLE
Addition: getSwatches() and setSwatches()

### ISSUE THREAD

**Issue by GreenFootballs** [Simonwep/pickr#241]
(This isn't really a feature request but it seemed like the best place to put it.)

In an app I'm developing we needed a way to easily save and load sets of color swatches, and since other people may also find this useful, here's the code I implemented to add these functions to Pickr.

```js
Pickr.prototype.getSwatches = function() {
    return this._swatchColors.reduce( (arr, swatch) => {
        arr.push(swatch.color.toRGBA().toString(0))
        return arr
    }, [] )
}
Pickr.prototype.setSwatches = function(swatches) {
    if (!swatches.length) return
    for (let i = this._swatchColors.length - 1; i > -1; i--) {
        this.removeSwatch(i)
    }
    swatches.forEach( swatch => this.addSwatch(swatch) )
}
```

You pass an array of CSS colors to setSwatches(), same format as the swatches array in Pickr's create options. getSwatches() returns an array in the same format.

**Comment by Simonwep** [comment]
Great addition :) But as [stated in the readme](https://github.com/Simonwep/pickr#status-of-this-project) features won't be added anymore, maybe we could move that to [EXAMPLES.md](https://github.com/Simonwep/pickr/blob/master/EXAMPLES.md)?

**Comment by GreenFootballs** [comment]
Sure, that's OK by me.
