### ISSUE TITLE
Customising the look of the colour picker

### ISSUE THREAD

**Issue by DexterHill0** [Simonwep/pickr#242]
I am requesting a feature of being able to customise all colours like background, buttons and text. That would make the picker very easily fit in any theme.

At the moment I have edited the css to change the colour to fit my dark theme. This is not ideal since I would have to do this any time I updated the library. I think the best way to do it would be to include some more options like:
```
colours: {
    save-button: #your-colour,
    background: #colour,
}
```
which would then adjust the css, changing the look of the entire colour picker.

I also just want to point out that after changing the background colour in the `.pcr-app` section, the colour preview circle will have a very unclean edge:
![Screenshot 2020-09-01 at 09 42 55](https://user-images.githubusercontent.com/49513414/91829384-4f8aaa00-ec39-11ea-8029-160329c766a7.png)
I found to get rid of this you have to remove:
```
background: url('data:image/svg+xml;utf8, <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2 2"><path fill="white" d="M1,0H2V1H1V0ZM0,1H1V2H0V1Z"/><path fill="gray" d="M0,0H1V1H0V0ZM1,1H2V2H1V1Z"/></svg>');
```
from in the `.pcr-app[data-theme="nano"] .pcr-selection .pcr-color-preview .pcr-current-color:before` section which then gives you:
![Screenshot 2020-09-01 at 09 43 05](https://user-images.githubusercontent.com/49513414/91829662-a6907f00-ec39-11ea-86de-a4a49b2003a5.png)

**Comment by Simonwep** [comment]
See the [status of this project](https://github.com/Simonwep/pickr#status-of-this-project). Either use the css-classes (which are fixed btw.)... adding variables for each individual element would be insane. It's already too much.
