### ISSUE TITLE
Error use Pickr with Vue

### ISSUE THREAD

**Issue by phanhuyanh** [Simonwep/pickr#244]
Error ```Cannot read property 'parentNode' of null``` When I use ```import Pickr from "@simonwep/pickr";````

**Comment by Simonwep** [comment]
Please stick to the [Issue Template](https://github.com/Simonwep/pickr/blob/master/.github/ISSUE_TEMPLATE.md). Create a JSFiddle and describe what you've done as detailed as possible and break your issue down to a minimum. This will help me to resolve it as fast as possible.
