### ISSUE TITLE
Let do this for Reactjs

### ISSUE THREAD

**Issue by caohv** [Simonwep/pickr#247]
I have problem when use this in React js. Pls do this for React js. Thanks

**Comment by Simonwep** [comment]
Please stick to the [Issue Template](https://github.com/Simonwep/pickr/blob/master/.github/ISSUE_TEMPLATE.md). Create a JSFiddle and describe what you've done as detailed as possible and break your issue down to a minimum. This will help me to resolve it as fast as possible.
