### ISSUE TITLE
Add color to palette

### ISSUE THREAD

**Issue by trushpatel97** [Simonwep/pickr#252]
After choosing a color from the color picker, is there a way save a color to the swatches? 

Like I know you can manually enter colors to the swatches, but is there a way I can pick a random color and add it to the list of swatches?

**Comment by Simonwep** [comment]
See [Methods](https://github.com/Simonwep/pickr#methods) - `pickr.addSwatch([color])`. Just listen to the `save` [event](https://github.com/Simonwep/pickr#events) and add the color afterwards ;)

**Comment by yairEO** [comment]
it would be nice if there was a setting which allows any color picked to **automatically** be added to the swatch palette (as FIFO). It is highly-likely in many situations that one picked color would also be needed in another color input. I have for example 20+ color inputs, and in some, the user will most likely want to reuse a few of the colors they already picked.

**Comment by Simonwep** [comment]
Since you can do it _that_ easily by just adding one line I wouldn't want to add this as an feature (and because it's feature-locked right now).

Example: https://jsfiddle.net/ztekfbLo/
You can, of course, use the `.hide()` method to hide it when a color has been set.
