### ISSUE TITLE
Div should not be removed when destroy()

### ISSUE THREAD

**Issue by hughanderson4** [Simonwep/pickr#259]
When call `destroy()` the container div is removed from DOM.
That was my div, expect lib to not delete it.
In my case, pickr must be created/destroyed sometimes based on other conditions on page.
When destroy and try to reopen, container div was removed.

Actually, container div was removed when pickr was created.
Suggest to not replace it, just fill it.
That way when destroy, you could leave div in same state as before pickr.

**Comment by Simonwep** [comment]
[`destroy()` does not remove anything at all](https://jsfiddle.net/f726qewn/), also see [methods](https://github.com/Simonwep/pickr#methods)

Also:
Please stick to the [Issue Template](https://github.com/Simonwep/pickr/blob/master/.github/ISSUE_TEMPLATE.md). Create a JSFiddle and describe what you've done as detailed as possible and break your issue down to a minimum. This will help me to resolve it as fast as possible.
