### ISSUE TITLE
Remove spamming `console.log`

### ISSUE THREAD

**Issue by GriefCode** [Simonwep/pickr#26]
#### Do you want to request a **feature** or report a **bug**? 
bug

#### What is the current behavior?
`console.log` when using `appendToBody`
https://github.com/Simonwep/pickr/blob/master/src/js/pickr.js#L299

#### If the current behavior is a bug, please provide the steps to reproduce.
Use `appendToBody` as config

#### What is the expected behavior?
No console log
#### Your environment:
```
Pickr-version: 0.1.9 - also present on master branch, see url
Browser-version:  Chrome 68
```

**Comment by Simonwep** [comment]
Oops, shouldn't be there 😬
