### ISSUE TITLE
Feature Request: Fire save when enter key is pressed in text input

### ISSUE THREAD

**Issue by hughanderson4** [Simonwep/pickr#261]
Hello, we need to suppress the built in save button, since we have pickr in a modal with it's own save button, to match our UX.
But when user presses enter keyboard key in text input field, no `save` is raised.

Please, it would help with accessibility and usability, and to match other UX of our app, if we could fire an event at the time user presses enter in text field.  Perhaps it is `save` event or perhaps other new event for representation of "enter key pressed".

Thank you for considering it.

**Comment by Simonwep** [comment]
[Here you go](https://jsfiddle.net/c3zdu0h5/). It's all documented and in 90% you can just do it yourself using the API - no need to change the lib itself. And **please** use the issue template the next time you open an issue (it won't be here), it helps us maintainers to quickly orient ourselves and solve issues as fast as possible.
