### ISSUE TITLE
Bootstrap modal

### ISSUE THREAD

**Issue by abatalib** [Simonwep/pickr#263]
Hi,

i try to use it in bootstrap modal page, but that not work.
PS : the modal page is generate with jquery

**Comment by Simonwep** [comment]
Please stick to the [Issue Template](https://github.com/Simonwep/pickr/blob/master/.github/ISSUE_TEMPLATE.md). Create a JSFiddle and describe what you've done as detailed as possible and break your issue down to a minimum. This will help me to resolve it as fast as possible.
