### ISSUE TITLE
How to hide the color-mixer with css?

### ISSUE THREAD

**Issue by gregnau** [Simonwep/pickr#267]
On smaller screens in landscape mode it takes the most of the viewport space,
while a hue slider would be enough for the task.

Is it possible to hide or remove somehow the color mixer with css?

So far i tried with the `display: none` property, but it causes the mixer output only `#NaNNaNNaN` for choosen color.

**Comment by Simonwep** [comment]
Please stick to the [Issue Template](https://github.com/Simonwep/pickr/tree/master/.github/ISSUE_TEMPLATE). Create a JSFiddle and describe what you've done as detailed as possible and break your issue down to a minimum. This will help me to resolve it as fast as possible.
