### ISSUE TITLE
There is noway to add tooltip for each color in swatches

### ISSUE THREAD

**Issue by pdutie94** [Simonwep/pickr#279]
#### Your environment:
```
Version (see Pickr.version):
Used bundle (es5 or normal one):
Used theme (default is classic): 
Browser-version:  
Operating-system:  
```

**Comment by Simonwep** [comment]
Please stick to the [Issue Template](https://github.com/Simonwep/pickr/tree/master/.github/ISSUE_TEMPLATE). Create a JSFiddle and describe what you've done as detailed as possible and break your issue down to a minimum. This will help me to resolve it as fast as possible.
