### ISSUE TITLE
Interactions for color is unknown

### ISSUE THREAD

**Issue by hcomnetworkers** [Simonwep/pickr#28]
#### Do you want to request a **feature** or report a **bug**? 
feature

#### What is the current behavior?
The interaction options for colors are static, it is not configureable which interaction option is choosen initial. Currently, per default, HEX is selected.
Additional, the selected interaction option for color is not directly accessible when saving.

#### What is the expected behavior?
The initial selected color interaction option should be defineable in the options - or automatically determined on the default value.
I am using an input field next to the pickr widget where the user is allowed to enter an RGBa String or a HEX code, it is confusing opening the widget with HEX selected when a RGBa String was given.

Furthermore, the `onSave` or `onChange` method should be aware which interaction option is currently active. So the return value can be either HEX or a RGBa String in my case.

#### Your environment:
```
Pickr-version: 0.1.9
Browser-version:  Chrome 68
```

**Comment by Simonwep** [comment]
Yeah, the possibility to change the color-representation would be helpful 😄 
Using the current branch you can use the option `defaultRepresentation`:
```js
// Possible values are RGBA, HSVA, HSLA and CMYK
defaultRepresentation: 'HEX'
```
or change it just-in-time using `pickr.setColorRepresentation(type)`.
It returns false if the type does not exist or is incorrect.
Currently not in any release, so currently not in README documented.

**Comment by hcomnetworkers** [comment]
Nice, now an option to get the color representation would be missing.
Something like `pickr.getColorRepresentation()`.

Thanks again for your work.

**Comment by Simonwep** [comment]
Ugh, yes... make sense. Sometimes I don't really plan ahead 😆 
No problem :) Every idea / issue improves this lib 😃

**Comment by Simonwep** [comment]
Added in db8790c5baeae182d47cd5e1ffb393986d6c5ba4 :) Should be included in `0.2.2`... however.

**Comment by Simonwep** [comment]
Oh, of course! I'll take a look later :)

**Comment by Simonwep** [comment]
Okay, `0.2.3` is available on npm! Seems like I forgot to publish it, npm needs also a little bit of time to refresh :)
