### ISSUE TITLE
.off is not unbinding event listener

### ISSUE THREAD

**Issue by macbubi** [Simonwep/pickr#280]
#### What is the current behavior?
We use this amazing color picker with custom events for 'clear', 'cancel', and 'change'.
The problem is that the events are not unsubscribed using the off method (the callback doesnt being called at all)

#### Please provide the steps to reproduce and create a [JSFiddle](https://jsfiddle.net/Simonwep/qx2Lod6r/).

https://jsfiddle.net/2m7tzybc/7/

#### What is the expected behavior?
.off(event, cb) will remove the event listener and call the cb function

#### Your environment:
```
Version (see Pickr.version): 1.8.0
Used bundle (es5 or normal one): es5
Used theme (default is classic):  nano
Browser-version:  chrome 90
Operating-system:  macOS
```

**Comment by Simonwep** [comment]
This is not how functions work... You pass in a function and try to unbind an different function in your fiddle. You'll need to declare a function which you can bind _and_ unbind.

Example:
```ts
pickr.on('change', console.log);
pickr.off('change', console.log);
```

or

```ts
const listener = () => console.logt('change!');
pickr.on('change', listener);
pickr.off('change', listener);
```
