### ISSUE TITLE
About make a color pick as a requirement

### ISSUE THREAD

**Issue by dantagle** [Simonwep/pickr#282]
Thank you for the pickr... my question is if there is a way to make the users to choose a color as a requirement? i mean to cant continue navigating until the user pick a color with pickr ?... thank you

**Comment by Simonwep** [comment]
Please stick to the [Issue Template](https://github.com/Simonwep/pickr/tree/master/.github/ISSUE_TEMPLATE). Create a JSFiddle and describe what you've done as detailed as possible and break your issue down to a minimum. This will help me to resolve it as fast as possible.
