### ISSUE TITLE
When you click on the Clear button, the X overlay is not visible

### ISSUE THREAD

**Issue by vkurko** [Simonwep/pickr#283]
#### What is the current behavior?
When you click on the Clear button, the X overlay is not visible.

#### Please provide the steps to reproduce and create a [JSFiddle](https://jsfiddle.net/Simonwep/qx2Lod6r/).

1. Open https://simonwep.github.io/pickr/
2. Click on the color button to show the color picker
3. Click Clear button

#### What is the expected behavior?
The color button gets transparent and a X overlay is added to indicate that there's no color selected.
#### Your environment:
```
Version (see Pickr.version): 1.8.1
Used bundle (es5 or normal one): es5
Used theme (default is classic): classic
Browser-version: Chrome 89.0.4389.114
Operating-system:  Ubuntu 20.04
```

**Comment by vkurko** [comment]
It looks like the X overlay was broken in this [commit](https://github.com/Simonwep/pickr/commit/6e5d0fef71ea819888e22d1fbfbf1fae6f6c83ea) - not all places in the code were replaced with css variables.

For the same reason, the `comparison` option no longer works.

**Comment by Simonwep** [comment]
Okay, related to #286

**Comment by vkurko** [comment]
@Simonwep thank you for fixing the issue. Will you publish v1.8.2 to npm? It is still 1.8.1 there.
