### ISSUE TITLE
`el` is forcibly replaced with a `div` Element

### ISSUE THREAD

**Issue by zepumph** [Simonwep/pickr#289]
#### What is the current behavior?

When I pass in an element that is a `span` for the button to be added to, creating a pickr swaps that out for a `div` with no explanation.

#### Please provide the steps to reproduce and create a [JSFiddle](https://jsfiddle.net/Simonwep/qx2Lod6r/).

Take the above fiddle, and swap the `div.pickr` for a `span`

#### What is the expected behavior?

When I pass in a `span` as the `el` option, it should stay a `span`

#### Your environment:
```
Version (see Pickr.version): 1.8,1
Used bundle (es5 or normal one): both, but mostly the es5
Used theme (default is classic):  classic
Browser-version:   Version 91.0.4472.124 (Official Build) (64-bit)
Operating-system:   Window 10 version 10.0.19041 Build 19041
```

Thanks for taking a look!

**Comment by Simonwep** [comment]
The [options](https://github.com/Simonwep/pickr#options) say:

```
    // Don't replace 'el' Element with the pickr-button, instead use 'el' as a button.
    // If true, appendToBody will also be automatically true.
    useAsButton: false,
```

And since `false` _is_ the default value it'll be replaced. The `el` property without `useAsButton: true` is merely an anchor point for where pickr should be mounted :)

**Comment by zepumph** [comment]
I see thanks. Thanks. That is helpful. Closing
