### ISSUE TITLE
Using the Dialogtag leads to an inaccessible pickr widget

### ISSUE THREAD

**Issue by hcomnetworkers** [Simonwep/pickr#29]
#### Do you want to request a **feature** or report a **bug**? 
bug

#### What is the current behavior?
Using the "dialog"-Tag as modal with a custom button results in an inaccessible pickr.

As noted in #22 the flag `appendToBody` is always true in that case. Which does not work with dialogs.

#### If the current behavior is a bug, please provide the steps to reproduce.
See: https://jsfiddle.net/xjvsfy0n/

#### What is the expected behavior?
Pickr should be open in front of the dialog.

#### Your environment:
```
Pickr-version: 0.1.9
Browser-version:  Chrome 68
Operating-system:  
```

**Comment by Simonwep** [comment]
Ugh, that's strange. Unfortunately I never used the dialog tag before. Did you have any idea why this happens?

**Comment by GriefCode** [comment]
The "Dialog"-Element allows a dialog being completely over the content. 
No element outside the dialog can overlap the dialog.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

This only applys to dialog elements being shown with `showModal()`, Using `show()` does makes the pickr widget being accessible: https://jsfiddle.net/xjvsfy0n/2/

A possible solution is locating the pickr-widget within the "Dialog"-Element.

**Comment by Simonwep** [comment]
I've dropped the `appendToBody` option, but added another one which is more universal. Until I've published a new version, here's the README snipped:

```js
// Defines a parent for pickr, if useAsButton is true and a parent is NOT defined
// 'body' will be used as fallback.
parent: `dialog` // As you already say "No element outside the dialog can overlap the dialog."
```

Updated and _working_ fiddle: https://jsfiddle.net/Ln26dpyq/1/ :)

**Comment by Simonwep** [comment]
I think this issue has been resolved, I close it for now. If problems regarding to it occur please reopen.
