### ISSUE TITLE
Lengthy Floating Point: Converting to RGBA

### ISSUE THREAD

**Issue by phuze** [Simonwep/pickr#293]
#### What is the current behavior?
When you convert a color to it's RGBA equivalent, it results in a rather lengthy floating point:

```js
pickr.setColor('#9C27B0')

console.log('themeHex', pickr.getColor().toHEXA().toString())
// returns #9C27B0

console.log('themeRgb', pickr.getColor().toRGBA().toString())
// returns rgba(156.00000000000006, 38.99999999999999, 176, 1)
```

#### Please provide the steps to reproduce and create a [JSFiddle](https://jsfiddle.net/Simonwep/qx2Lod6r/).

Look at the console in this fiddle:
https://jsfiddle.net/urp52z60/

#### What is the expected behavior?

A well-formed value that adheres to the expected RGBA color model.
Expected output: `rgba(156, 39, 176, 1)`

#### Your environment:
Version: `1.8.1`
Used bundle: `modern`
Used theme: `classic`
Browser-version: `Edge 92.0.902.67`
Operating-system: `Windows 10`

**Comment by phuze** [comment]
I'll follow this up by noting for anyone else reading, you can resolve this by mapping the array yourself:

```js
pickr.setColor('#9C27B0')

let fixedRgba =  `rgba(${pickr.getColor().toRGBA().map( num => { return Math.round(num) }).join(', ').toString()})`;

console.log('fixedRgba', fixedRgba)
// returns rgba(156, 39, 176, 1)
```

**Comment by saeedxnazari** [comment]
also you can use `.toString(0)`
`pickr.getColor().toRGBA().toString(0)`
it is documented on [readme](https://github.com/Simonwep/pickr#readme).

**Comment by Simonwep** [comment]
Correct way of solving this, thanks @saeedxnazari :)
