### ISSUE TITLE
Shadow

### ISSUE THREAD

**Issue by Ayan-Bhar** [Simonwep/pickr#299]
https://codepen.io/ayan-testing-purposes/pen/JjJmmNa

https://youtu.be/RHWGHbjCkno

**Comment by Simonwep** [comment]
Please stick to the [Issue Template](https://github.com/Simonwep/pickr/tree/master/.github/ISSUE_TEMPLATE). Create a JSFiddle and describe what you've done as detailed as possible and break your issue down to a minimum. This will help me to resolve it as fast as possible.
