### ISSUE TITLE
Create some peakers

### ISSUE THREAD

**Issue by haneate** [Simonwep/pickr#30]
How to create some color peakers? If I create some instance they crash page or stay on left top corner. Only first peaker work good.

Pickr-version: 0.2.0
Browser-version:  Chrome 68.0.3440.106
Operating-system:  ubuntu

**Comment by Simonwep** [comment]
Did you mean multiple instances?

**Comment by haneate** [comment]
Yes

**Comment by Simonwep** [comment]
Okay, I've tried to reproduce it: https://jsfiddle.net/35ukvpty/13/
But everything works as expected. Maybe there was an issue for version `0.2.0` cause `0.2.1` is out. But I've changed nothing relating to dom stuff.

Tested on `Chrome Canary 70.0.3530.0` on `Windows 10`

**Comment by Simonwep** [comment]
Did you solved it? If not could you please provide the steps to reproduce it? 
Or create a JSFiddle.

**Comment by Simonwep** [comment]
I'll close it because of inactivity.
