### ISSUE TITLE
Colors input not working in modals

### ISSUE THREAD

**Issue by 42plamusse** [Simonwep/pickr#300]
#### What is the current behavior?

When using Pickr in a bootstrap modal, the input isn't responding.

#### Please provide the steps to reproduce and create a [JSFiddle](https://jsfiddle.net/Simonwep/qx2Lod6r/).

https://jsfiddle.net/plamusse42/c08ajokb/10/

#### What is the expected behavior?

Input should be working.

#### Your environment:
```
Version (see Pickr.version): 1.8.2
Used bundle (es5 or normal one): es5
Used theme (default is classic): classic
Browser-version:  Chrome 93.0.4577.82
Operating-system:  macOS Big Sur
```

**Comment by friedrichkeydel** [comment]
@Simonwep same problem here!

**Comment by 42plamusse** [comment]
@friedrichkeydel I found out that this is not an issue with this library but with bootstrap modals. Solution to our problem in here: https://github.com/sweetalert2/sweetalert2/issues/374#issuecomment-268802123

**Comment by friedrichkeydel** [comment]
@42plamusse thank you, that indeed solved it! ;)
