### ISSUE TITLE
getColor method needs to be highlighted on the docs. #Suggestion

### ISSUE THREAD

**Issue by nzee** [Simonwep/pickr#302]
Just a suggestion here to highlight the key method that fetches the hex value on the main docs.

`let hexColorPicked = pickr.getColor().toHEXA().toString()`

**Comment by Simonwep** [comment]
Please stick to the [Issue Template](https://github.com/Simonwep/pickr/tree/master/.github/ISSUE_TEMPLATE). Create a JSFiddle and describe what you've done as detailed as possible and break your issue down to a minimum. This will help me to resolve it as fast as possible.
