### ISSUE TITLE
Conflict between clear and change events

### ISSUE THREAD

**Issue by Kazem-ma79** [Simonwep/pickr#311]
There's a problem while calling clear event, which calls change event.

When I press clear button, change event runs.

#### Code:
```
pickr.on('cancel', (instance) => {
    let request = new XMLHttpRequest();
    request.open("GET", "/off");
    request.send();
}).on('clear', (instance) => {
    let request = new XMLHttpRequest();
    request.open("GET", "/lightup");
    request.send();
}).on('change', (color) => {
    let hex = color.toHEXA();
});
```
#### Environment:
```
Version (see Pickr.version): 1.8.2
Used bundle (es5 or normal one): normal
Used theme (default is classic): classic
Browser-version:  Chrome 96
Operating-system:  Windows 10 - 64bit
```

**Comment by saeedxnazari** [comment]
the conflict between Clear and Change events or Clear and Save events? you mentioned in another topic about the conflict between save and clear event.

I do not think this plugin will be updated anymore. 
I struggled a lot with changing default buttons actions and to some extent, I got the desired result, but again, in the end, there was a problem and undesired behavior.

Finally, I decided to add buttons myself and I could do whatever I wanted without any problems. 
Why you don't add buttons to this plugin yourself? You will not have any possible problems.

I added a video and you can see my implemented buttons:
https://github.com/Simonwep/pickr/issues/310

just my 2 cents:)

**Comment by Simonwep** [comment]
This works as intended, clearing it is technically a change...
