### ISSUE TITLE
Readme: Node setup instructions incorrect

### ISSUE THREAD

**Issue by JulianSchoenbaechler** [Simonwep/pickr#32]
#### Do you want to request a **feature** or report a **bug**? 
bug, kinda...

#### What is the current behavior?
Importing instructions for using pickr in node use currently a destructuring pattern that is not necessary and lead to an error ('Pickr' is undefined):
```js
import {Pickr} from '/node_modules/pickr-widget/dist/pickr.min';  // Javascript
```

#### What is the expected behavior?
The imported script already returns a function that represents the Pickr object, so destructuring is not needed.
```js
import Pickr from '/node_modules/pickr-widget/dist/pickr.min';  // Javascript
```

#### Your environment:
```
Pickr-version: 0.2.2
Node-version: v8.11.3
Operating-system: Windows 10, 1803
```

**Comment by Simonwep** [comment]
Oops, well.. seems like i've changed the export type. Thanks for reporting it 👍 
I'll change it!
