### ISSUE TITLE
Error - Property 'app' does not exist on type 'object'.

### ISSUE THREAD

**Issue by ghost** [simonwep/pickr#320]
#### What is the current behavior?

For following
```js
const pickrApp = pickr.getRoot().app;
```

Getting error
```error
Property 'app' does not exist on type 'object'.
```

![image](https://user-images.githubusercontent.com/120771048/218088255-531db0d7-e911-4314-98f4-4e2e7041392b.png)

#### What is the expected behavior?

There should a function to get app.
```
const pickr = pickr.getApp()
```

#### Your environment:
```
Version (see Pickr.version):
Used bundle (es5 or normal one):
Used theme (default is classic): 
Browser-version:  
Operating-system:  
```

**Comment by simonwep** [comment]
You must wait for the `init` event to access the DOM.
