### ISSUE TITLE
Broken initialization when using `useAsButton`

### ISSUE THREAD

**Issue by hcomnetworkers** [Simonwep/pickr#33]
#### Do you want to request a **feature** or report a **bug**? 
bug

#### What is the current behavior?
The pickr does not initialize and throws an error.

#### If the current behavior is a bug, please provide the steps to reproduce.
Check the fiddle:
https://jsfiddle.net/hnwbqmLt/3/

#### What is the expected behavior?
Initialization and no errors... I guess it is related to #31 .

#### Your environment:
```
Pickr-version: 0.2.3 / master
Browser-version:  Chrome 68
```

**Comment by Simonwep** [comment]
Okay, the core code is slowly getting complicated 😅  
Updated fiddle: https://jsfiddle.net/hnwbqmLt/5/
Maybe I'll write some tests at the weekend, but currently I've got no time for that :/
