### ISSUE TITLE
Bug: hex text-field not working correctly when alpha channel is disabled

### ISSUE THREAD

**Issue by Larzans** [Simonwep/pickr#34]
#### Do you want to request a **feature** or report a **bug**? 
Bug

#### What is the current behavior?
When changing the text-hex value the color becomes transparent when only 3 characters are shown, instead of when there are 4

#### If the current behavior is a bug, please provide the steps to reproduce.
Disable alpha channel via opacity: false
Start removing characters from the displayed hex value
Nothing happens when there are 4 characters (but it should as it doubles to RRGGBBAA)
When there are 3 characters it suddenly shows transparency

Example color used: #FFAAFF

#### What is the expected behavior?
4 characters should represent transparency, 3 should be a solid color

#### Your environment:
```
Pickr-version: 0.2.4
Browser-version:  Chrome  68.0.3440.106 (latest), same in FF
Operating-system:  Win7
```

**Comment by Simonwep** [comment]
Okay, the problem was a recalculation which happend after you deleted a character. So when you press `delete` on `#FFAA` it would stay the same until you press delete again, then it would be `#FFA`.

Anyway, I've fixed it (hopefully) in 2be871af51f4f2f1a0bfe30231da2413260ce5ef :)

**Comment by Larzans** [comment]
Nice, you did indeed.
Thanks for the quick fix :+1:

**Comment by Simonwep** [comment]
Your'e welcome :)
