### ISSUE TITLE
Color is not selected when clicking, only when dragging

### ISSUE THREAD

**Issue by xyannik** [Simonwep/pickr#35]
#### Do you want to request a **feature** or report a **bug**? 
Bug.

#### What is the current behavior?
Clicking into either the Hue-palette, the luminosity slider or the transparency slider does not set the value to where the user clicked. Only once the user drags (even 1px), the color is updated.

#### If the current behavior is a bug, please provide the steps to reproduce.
Go to https://jsfiddle.net/dL0e569h/1/ or to the official demo https://simonwep.github.io/pickr/ and open the color picker. Click anywhere into the hue palette _without_ moving the mouse while clicking. Nothing happens. But keep the mouse button pressed, and drag a few pixels, and the color is picked.

#### What is the expected behavior?
The color should be updated just by clicking, without dragging. The `pcr-picker` circle should move to where the user clicked.

#### Your environment:
```
Pickr-version: Newest from npm (0.2.4)
Browser-version:  Google Chrome 69.0.34
Operating-system:  Windows 10 Home
```
I'd be happy if someone could help me out or offer a workaround. Thanks!

**Comment by Simonwep** [comment]
Yeah, seems like this was possible until I removed something which I thought was useless...  

![Alt Text](https://i.redd.it/hfnl7xo8yovy.gif)

Fixed / re-added in 2f75f28b567de351606a4489a4c4fa881b7c87e0 :)
You can use the current master version, there are also some other bug-fixes. I'll publish a new version in a few days.

**Comment by Larzans** [comment]
I can confirm that the fix works for me.
Although i have to admit that it was not a consistent behaviour before, sometimes it would work, sometimes not, i couldn't figure out the trigger...

**Comment by xyannik** [comment]
Agree with Larzans, the bug only appeared sometimes, but lately it showed up more often than not (maybe due to a Chrome update? IDK). 
Glad to hear this got fixed so quickly, thank you Simon! I corfirm too that the fix works :)
