### ISSUE TITLE
Incorrect color-converting

### ISSUE THREAD

**Issue by zakiyama01** [Simonwep/pickr#38]
show https://simonwep.github.io/pickr/
open pickr
input C66016
click "HEX"
change input #C76117

**Comment by zakiyama01** [comment]
use setColor()
same onSave result

**Comment by Simonwep** [comment]
Yeah, this problem occurs again and again, #27 was basically the same. It's cause of rounding errors... I try to solve it, but any help would be appreciated!

**Comment by Simonwep** [comment]
I switched back to round in 572977ce0d81aabfe05a4974811140442e14135e, this has solved the problem in your case but I'm quite not sure if this is the best solution.

**Comment by zakiyama01** [comment]
show https://simonwep.github.io/pickr/
open pickr
input `#0132D063`
click RGBa and HEX
change `#-3001D063`

**Comment by Simonwep** [comment]
Ya, seems like I've destroyed the `hsvToRgb` function in 572977ce0d81aabfe05a4974811140442e14135e , reverted in 954f46a2b27d3908c7ec6a3a60817cedaa0d0095. Never change a running system 😄

**Comment by Simonwep** [comment]
I'll close it for now, maybe I or someone find another / better way to handle the color states, I would open it again.
