### ISSUE TITLE
Layout bug on Chrome 69. Fix suggestion.

### ISSUE THREAD

**Issue by deniskabalkin** [Simonwep/pickr#39]
Just got layout bug. Reproduced on clean page (only Pickr included).
`<div class="pcr-color-palette">` overlapped interaction bar. 
Here is image:
<img width="261" alt="pickr_bug" src="https://user-images.githubusercontent.com/667998/46958156-d49a6380-d0a1-11e8-9e21-cfe77bb555a6.png">

This is my fix suggestion (cannot create PR right now, sorry): 
line 213 of .css file
`.pcr-app .pcr-selection .pcr-color-chooser,
.pcr-app .pcr-selection .pcr-color-opacity,
.pcr-app .pcr-selection .pcr-color-palette {
    position: relative;
    user-select: none;
    display: flex; /* ADDED */
    flex-direction: column;  /* ADDED */
}`

This fixed problem for me

#### Your environment:
```
Pickr-version: 0.2.5
Browser-version:  Chrome Version 69.0.3497.100 (Official Build) (64-bit)
Operating-system:  macOs High Sierra 10.13.6
```

**Comment by Simonwep** [comment]
Seems like there is an issue with Chrome on Mac... unfortunately I don't own one and cannot test it correctly. A PR with modified `.scss` files would be awesome! :)

**Comment by deniskabalkin** [comment]
Created PR: #41
