### ISSUE TITLE
Pickr sliders and output acting up on page load

### ISSUE THREAD

**Issue by datitisev** [Simonwep/pickr#4]
#### Do you want to request a **feature** or report a **bug**? 

Bug

#### What is the current behavior?

Pickr initializes with `#NANNANNAN` even though the default is set to `#FF1294` (which you can see in the preview of the last color saved).
The sliders are 100% not working and when clicking the transparency one, the resulting hex value is negative because the selected point is somewhere completely different (no idea where).

#### If the current behavior is a bug, please provide the steps to reproduce.

I used the following code, and just appended the `.pickr` div before initializing Pickr with that element (which seems to work just fine).

```js
import Pickr from "pickr-widget/dist/pickr.min";

new Pickr({
  el: $(".pickr"),

  default: "#FF1294",

  components: {
    preview: true,
    opacity: true,
    hue: true,

    output: {
      hex: true,
      rgba: true,
      hsva: true,
      input: true
    }
  }
});
```

The weird thing is that the demo at https://simonwep.github.io/pickr/ seems to work just fine...
I am not sure of the exact root cause of this problem.
I don't want to show much of my code, but it works fine when I execute it from Devtools (shows expected behavior) but not from JS.
I am using Rollup with CommonJS, and am importing the dist file directly via `import Pickr from 'pickr-widget/dist/pickr.min';`

#### What is the expected behavior?

The output color is completely normal and the sliders work properly.

#### Your environment:
```
Pickr-version: 61a7ff46a11d9fc84da428fd826a2d03634b9456
Browser-version: Google Chrome Version 68.0.3440.17 (Official Build) beta (64-bit)
Operating-system:  macOS High Sierra 10.13.5
```

![image](https://user-images.githubusercontent.com/6401250/41323084-68c5ca5c-6e7a-11e8-8bf9-13f277bc19ea.png)

**Comment by Simonwep** [comment]
That's strange, could you please provide some Information how to reproduce it? Maybe your `rollup` build config. How about errors? Seems like a lot is crashing.

**Comment by datitisev** [comment]
There are no errors in console.I could provide the Pickr instance object if you want, but I’ll try to find the root cause later today when I have time.

**Comment by datitisev** [comment]
<details>
<summary><code>Pickr</code> object after initializing:</summary>
<p>

  ```json
{
  "options": {
    "components": {
      "preview": true,
      "opacity": true,
      "hue": true,
      "output": {
        "hex": true,
        "rgba": true,
        "hsva": true,
        "input": true
      }
    },
    "default": "#000",
    "el": {}
  },
  "root": {
    "root": {},
    "button": {},
    "app": {},
    "input": {
      "options": {
        "0": {},
        "1": {},
        "2": {},
        "3": {},
        "4": {}
      },
      "result": {},
      "save": {}
    },
    "preview": {
      "lastColor": {},
      "currentColor": {}
    },
    "palette": {
      "picker": {},
      "palette": {}
    },
    "hueSlider": {
      "picker": {},
      "slider": {}
    },
    "opacitySlider": {
      "picker": {},
      "slider": {}
    }
  },
  "inputActive": false,
  "color": {
    "h": 0,
    "s": 0,
    "v": 0,
    "a": 1
  },
  "lastColor": {
    "h": 0,
    "s": 0,
    "v": 0,
    "a": 1
  },
  "components": {
    "palette": {
      "options": {
        "lockX": false,
        "lockY": false,
        "element": {},
        "wrapper": {}
      },
      "cache": {
        "x": 0,
        "y": 0
      }
    },
    "hueSlider": {
      "options": {
        "lockX": true,
        "lockY": false,
        "element": {},
        "wrapper": {}
      },
      "cache": {
        "x": 0,
        "y": 0
      }
    },
    "opacitySlider": {
      "options": {
        "lockX": true,
        "lockY": false,
        "element": {},
        "wrapper": {}
      },
      "cache": {
        "x": 0,
        "y": 0
      }
    },
    "selectable": {
      "options": {
        "className": "active",
        "elements": {
          "0": {},
          "1": {},
          "2": {},
          "3": {},
          "4": {}
        }
      }
    }
  }
}
```
</p>
</details>
<br />

I've found out that Pickr seems to load completely fine if I have a timeout of >83ms after `DOMContentLoaded` is fired.
I'm not sure why this is the case at all. I initialize Pickr right after the DOM has loaded.

If helpful, here is how I build my dist file:
- rollup bundle w/ `rollup`
  - plugins
    - `rollup-plugin-node-resolve` (browser)
    - `rollup-plugin-commonjs` (browser, `node_modules/**`)
    - `rollup-plugin-terser` (toplevel, ie8, safari10)
      - didn't work before I even added this plugin
  - output
    - format: `iife`
    - sourcemaps

**Comment by Simonwep** [comment]
Okay, I've finally reproduced the problem. This behavior occurs if you load the `pickr.min.css`, which is saved under `node_modules/pickr-widget/pickr.min.css`, **after** your `.js` file.

In my case, it worked for me if I put the `<link rel="stylesheet" href="path-to/pickr.min.css">` in my `head` tag or somewhere before my `.js` file which contains the `pickr` instance.

**Comment by datitisev** [comment]
Hm, yeah, I see that's the issue. Moving the JavaScript file to load after my bundled CSS fixed it, though I'm not sure why that would ever be an issue.

This bug seems to also occur if the `script` tag also has the `defer` attribute, removing it AND loading it after the CSS fixed the problem.

**Comment by Simonwep** [comment]
I'm glad you like it :)
Good idea, I will mention it in the README!
