### ISSUE TITLE
Color picker closes on click over the palette when useAsButton: false and parent: 'body'

### ISSUE THREAD

**Issue by amrtn** [Simonwep/pickr#40]
#### Do you want to request a **feature** or report a **bug**? 
Bug

#### What is the current behavior?

A click inside the palette will close the color picker when pickr is created with `useAsButton: false` and `parent: 'body'`

![2018-10-16_15-28-00](https://user-images.githubusercontent.com/151747/47020866-92812880-d15a-11e8-9dff-36f833e02930.gif)

#### If the current behavior is a bug, please provide the steps to reproduce.

```js
const pickr = new Pickr({
    el: '.color-picker',

    default: '#42445A',
    useAsButton: false,
    parent: 'body',

    components: {

        preview: true,
        opacity: true,
        hue: true,

        interaction: {
            hex: true,
            rgba: true,
            hsva: true,
            input: true,
            clear: true,
            save: true
        }
    }

});
```

#### What is the expected behavior?

The palette is kept open on click. The pallete is closed when the **Save** button is clicked or the user clicks outside the color picker.

#### Your environment:
```
Pickr-version: master branch, latest commit: 954f46a
Browser-version:  Chrome 72.0.3581.0 (Official Build) canary (64-bit)
Operating-system:  Windows 10
```

**Comment by Simonwep** [comment]
Thanks for this picturesque issue-opening 😃  (and finding it), seems like this bug appeared as I added the `parent` option (or similar). I've fixed it in bdbd3b7cbf21f79c0f6e6a83db7585f2b5b3f666!
