### ISSUE TITLE
pcr-picker Coordinate initialization position is wrong

### ISSUE THREAD

**Issue by chenweibo** [Simonwep/pickr#42]
Why do I follow the demo initialization plugin to find that opacity is not 1 but 0? What do I need to do?
  
![2018-10-25 10 11 25](https://user-images.githubusercontent.com/19586007/47471802-912cbb80-d83e-11e8-94dc-9bc093e70007.png)

**Comment by chenweibo** [comment]
After initialization, the opacity is pulled to 1
find it 
![2018-10-25 10 26 57](https://user-images.githubusercontent.com/19586007/47472271-a99dd580-d840-11e8-9a91-96c62eb5f95f.png)

**Comment by Simonwep** [comment]
Could you please provide a [jsFiddle](https://jsfiddle.net) demo, or how this problem can be reproduced?

**Comment by Simonwep** [comment]
If you share your `webpack.config.js` I could try to reproduce / fix it.

**Comment by chenweibo** [comment]
@Simonwep   https://github.com/chenweibo/webpack4-template/tree/master/build .this config .
 run dev  Have this problem , run build  is success .
Everything is normal after packaging emmmm.

**Comment by Simonwep** [comment]
Closing it for now because of inactivity.
