### ISSUE TITLE
pickr.Show() Not working well

### ISSUE THREAD

**Issue by iBelit** [Simonwep/pickr#43]
hi
pickr.show not working with options:
useAsButton: true,        comparison: false

i can show pickr only by clicking on button! i need to show on INPUT TEXT focus

**Comment by Simonwep** [comment]
Could you please provide a [JSFiddle](https://jsfiddle.net) demo? I've tried it with your props but everything seems to work as expected [fiddle](https://jsfiddle.net/azpc5bmj/10/).

**Comment by iBelit** [comment]
[JSFiddle](https://jsfiddle.net/etb7kh9f/3/)
click on INPUT

**Comment by Simonwep** [comment]
Seems like event bubbling was the problem. If your clicking outside of pickr, it will close itself, also on input elements. Changed to `mousedown` and `touchstart` events to detect blurring, doesn't look like a good solution, but it works so far. (34d3e730f4e9e82373dd0dbd854cb07829783db5)

Updated Fiddle: https://jsfiddle.net/etb7kh9f/25/

**Comment by Simonwep** [comment]
If your're using npm, you can use `npm i git://github.com/Simonwep/pickr.git` to get the last commits (which includes this fix). Otherwise, dist is always up-to-date :)
