### ISSUE TITLE
Pickr button background invisible when ancestor background set

### ISSUE THREAD

**Issue by yamass** [Simonwep/pickr#48]
#### Do you want to request a **feature** or report a **bug**? 
Bug.

#### What is the current behavior?
When the background of any ancestor of the pickr is set, the pickr button's background (checkerboard pattern indicating transparent colors) is not visible.

#### If the current behavior is a bug, please provide the steps to reproduce.
* Go to https://simonwep.github.io/pickr/
* chose a color _with a low alpha value_
==> checkerboard pattern visible
* open developer tools
* Add the following style to the body tag: `background-color: white;`
==> checkerboard pattern no more visible

#### What is the expected behavior?
The checkerboard pattern should be visible.

#### Your environment:
```
Pickr-version: 0.3.1
Browser-version: Chrome, Firefox, Edge, ... (version-independent)
Operating-system:  Mac, Windows, ...
```

#### Analysis
The problem is caused by the following style: 

```css
.pickr .pcr-button:before {
    ...
    z-index: -1;
}
```
I suggest using another element for the color selection and setting the checkerboard patter background to the .pcr-button itself.

**Comment by yamass** [comment]
Very nice solution! Works great. I don't see any edge cases either (except for people using z-index 1 for something else).
Thank you for the quick fix!

**Comment by avribacki** [comment]
You are probably aware, but this issue was re-introduced in this commit: https://github.com/Simonwep/pickr/commit/ad59f93b95a2ef5b87a8d6f0774694cf72d611e5
Should this issue be re-opened?

**Comment by Simonwep** [comment]
@avribacki Ay damn, never thought about removing it! I'll take a look! Thank you for drawing my attention to it 😃
