### ISSUE TITLE
Feature request: Ability to choose "no color"

### ISSUE THREAD

**Issue by Finesse** [Simonwep/pickr#5]
It would be great if Pickr has an ability to select no color. "No color" is not the same as the fully transparent color. Selecting nothing can be used when there is a default color (e.g. page background) and a user can select either the default color or a custom color (to customise his background color).

**Comment by Simonwep** [comment]
To understand you correctly, you mean something like a reset-button which will set the current color back to default?

**Comment by Finesse** [comment]
@Simonwep I mean a button which makes the following when clicked:

1. `onChange` handler is called with `null` or something similar as the first argument.
2. The open button shows that a color is not chosen. For example, this way: ![image](https://user-images.githubusercontent.com/9006227/41457704-cfd55614-70c7-11e8-9712-0fbfdf72349e.png)

**Comment by Simonwep** [comment]
I've added the feature in 906e10cc1e41b7af7aa7e30158cd299fcc6d7da6 :)
There is also a new version available, [`0.1.0`](https://github.com/Simonwep/pickr/releases/tag/0.1.0), slowly it's going into beta phase, so it hasn't _fully_ backwards-compatibility. (It's only the method `cancel()` which doesn't exists anymore, and some changes in `hide()` and `show()`).

**Comment by JamoCA** [comment]
Is there any way to use `pickr.setColor()` to set unchosen color?  I'm additionally allowing an input field to be used and an empty field (0 length string; not NULL) is an option. I'm using setColor() to update the pickr button upon changing the value, but do not know how to programmatically set it to this new "no selection" option. Thanks.

**Comment by Simonwep** [comment]
@JamoCA This is currently not possible, but would be a great feature! I'll add it, probably, as you say, using `pickr.setColor(null)` would be the best option to remove it.

**Comment by Simonwep** [comment]
@JamoCA I've added it in 28bdf5ac2b86d2260e2d49fe0434294fabbdfa80 :)

**Comment by JamoCA** [comment]
The update works perfectly!  I usually automatically assign default colors if not specified by the user. I was interested in using this library, but it was a showstopper if users couldn't clear/reset selected colors.  Thanks!
