### ISSUE TITLE
pcr-picker position, CSS size override and percents

### ISSUE THREAD

**Issue by Evangeline-Rei** [Simonwep/pickr#53]
Hello! You did a great job, your colorpicker is awesome.
But, here is some issues. It's about pcr-app size.

**1 - CSS Override.**
If I set only .pcr-app class height, pcr-picker position is **correct**.
( here is a demo http://jsfiddle.net/o3e5wqc7/7/ )

If I set .pcr-app height as child of any **tag**, pcr-picker position is **correct**.
( here is a demo http://jsfiddle.net/o3e5wqc7/8/ )

If I set .pcr-app height as child of any **class**, pcr-picker position is **INCORRECT**.
(It takes a value of default style 240px)
( here is a demo http://jsfiddle.net/o3e5wqc7/9/ )

**2 - Size in percents**
I need to set height on .pickr and .pcr-app in percents, there is always position: 0 0 after intialization.
( here is a demo http://jsfiddle.net/o3e5wqc7/10/ )

I hope this is not a feature, but just an annoying little bug :)

**Comment by Simonwep** [comment]
Thanks, I'm glad you like it :)

![61218252 1](https://user-images.githubusercontent.com/30767528/50566272-f1a51100-0d37-11e9-8480-7b67aab86a3c.png)

Regarding to the first issue with CSS Overrides, wow - that's a really strange issue. Seem's like the browser applies some styles later than others. Anyway, it works if I wrap the first color-applying stuff into a `requestAnimationFrame`, see cfbc278e297f521ce66507d4db970616a45789b6.

To the second one, it works... at least on Chrome `71.0.3578.98`. I'll test it later on other browsers!

**Comment by Simonwep** [comment]
Oops, I'm a little bit confused about the second issue. Tried it in Chrome (canary and stable) and Firefox. Either this problem has been solved with the other bug fix, or I just used browsers in which this issue in particular isn't present. Which browser did you use?

**Comment by Evangeline-Rei** [comment]
After your fix its works fine. You can close this issue :3 Thank you again

**Comment by Simonwep** [comment]
You're welcome :)
