### ISSUE TITLE
onChange fires if a default color is specified

### ISSUE THREAD

**Issue by bediu** [Simonwep/pickr#54]
#### Do you want to request a **feature** or report a **bug**? 
bug
#### What is the current behavior?
`onChange` event fires immediately after creating a pickr object when specifying a default color using `default` in options 
#### What is the expected behavior?
`onChange` should not fire when specifying a default color
#### Your environment:
```
Pickr-version (see Pickr.version): 0.3.2
Browser-version:  Firefox 64
Operating-system:  Linux
```

**Comment by Simonwep** [comment]
Eh, may a result out of #53 Fixed in 828708b0766fd840c7af25d249be3f906d1ddfb9 :)
