### ISSUE TITLE
Deprecation Warning: Using unescaped '#' characters in a data URI.

### ISSUE THREAD

**Issue by okydk** [Simonwep/pickr#55]
I've been getting this deprecation warning the last couple of months, and hope we can fix it before functionality breaks in the latest Chrome. :)

`[Deprecation] Using unescaped '#' characters in a data URI body is deprecated and will be removed in M71, around December 2018. Please use '%23' instead.`
#### Environment:
```
Pickr-version (see Pickr.version): 0.3.2
Browser-version:  Chrome 71.0.3578.98
Operating-system: MacOS
```

**Comment by Simonwep** [comment]
Oh, of course! I'll take a look!
Thank's for drawing attention to it :)

**Comment by Simonwep** [comment]
Whoops I tried it both in `71.0.3578.98` and canary (`73.0.3670.0`) and I didn't saw any warning. Did you found this issue on the [demo page](https://simonwep.github.io/pickr/)? 

Also the only place where theoretically i could use `#` would be [here](https://github.com/Simonwep/pickr/blob/master/src/scss/variables.scss#L39). But all hashtags were properly escaped 🤔

**Comment by okydk** [comment]
I don't get any warnings on the demo-page. Might be something on my side then, but chrome reports the issues are found in `pickr.min.js?835f:1`.

I also get another warning regrading a event listener:
```
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
```

I'll investigate further! And sorry for the inconvenience, if it's entirely my part. Keep it up! :)

**Comment by Simonwep** [comment]
No problem :)
But, the second one is familiar to me. It's also a problem in selectionjs. I already tried adding `{passive: true}` [here](https://github.com/Simonwep/pickr/blob/master/src/js/pickr.js#L282) but I can remember I got an error after some time because I called `preventDefault()` somewhere and that's not possible in a passive event listener.

**Comment by Simonwep** [comment]
This was actually a problem [here](https://github.com/Simonwep/pickr/blob/76cf2df9f5af0f15b81a8cf9712eef1daa35a0f2/src/scss/lib/_variables.scss#L37). I fixed it using `%23` instead of `#` to declare hex colors.
