### ISSUE TITLE
Palette is empty

### ISSUE THREAD

**Issue by vix95** [Simonwep/pickr#62]
Hi mates, good job, your module is the best I've ever seen. I have a little problem in Chrome v49, so, palette is empty. I can't see. I can type a color by HEX but I can't select color by palette. Could you please look on this? Thanks! Below I attached a screen with issue. My console in browser is empty.
![bug](https://user-images.githubusercontent.com/38139321/52374832-8f3ddf80-2a5e-11e9-999d-868cc0ce52bd.png)

**Comment by Simonwep** [comment]
Chrome v49 is by far not included in [browserslistrc](https://github.com/Simonwep/pickr/blob/master/.browserslistrc), try to use the ES5 version introduced in #60.

First problem which would be is `String.prototype.padStart` which is not supported by this browser version [Can I Use padStart?](https://caniuse.com/#search=padStart).

**Comment by Simonwep** [comment]
Maybe also related to #59 and #36. Closing it because of inactivity.
