### ISSUE TITLE
hex value on IOS is an error.

### ISSUE THREAD

**Issue by liuyf** [Simonwep/pickr#63]
#### Do you want to request a **feature** or report a **bug**? 
I want to report a bug.

#### What is the current behavior?
I integrate this component into my Ionic3.x project.
When I run on IOS webkit, the hex value is '#NANNANNAN'

**Comment by Simonwep** [comment]
Unfortunately I don't have access to an iOS device. Could you provide the steps how to reproduce it? Maybe a JSFiddle :)

**Comment by Simonwep** [comment]
Which iOS version did you use? Did you checked if it is covered by .browserlistsrc?
I'll close it for now because of inactivity.
