### ISSUE TITLE
Adding an onCreate event hook

### ISSUE THREAD

**Issue by st-spark** [Simonwep/pickr#64]
Before updating to latest version of Pickr, event onChange was firing after full creation of pickr.

I suggest to add event "onCtreate".

**Comment by Simonwep** [comment]
This was initially a _bug_ or more an unwanted feature introduced and fixed in #17. I'll consider a `onCreate` or `onInit` function which will be called on initialization.

**Comment by Simonwep** [comment]
Available since `0.4.0` with event hooks. See [events](https://github.com/Simonwep/pickr#events) :)
