### ISSUE TITLE
ES5 version not downloading from NPM

### ISSUE THREAD

**Issue by jonathanwoahn** [Simonwep/pickr#65]
#### Do you want to request a **feature** or report a **bug**? 
Bug

#### What is the current behavior?
ES5 version of application is not downloading from NPM

#### What is the expected behavior?
I would expect to be able to import the ES5 version as described in the readme.

**Comment by Simonwep** [comment]
The ES5 bundle is currently in no version available. See https://github.com/Simonwep/pickr/compare/0.3.4...master

**Comment by Simonwep** [comment]
Okay, decided to publish [v0.3.5](https://www.npmjs.com/package/pickr-widget/v/0.3.5) which includes the es5 bundle, seems like many want to use it...
