### ISSUE TITLE
Event driven system

### ISSUE THREAD

**Issue by Simonwep** [Simonwep/pickr#66]
Since all these `onXYZ` callbacks don't seem to be so effective related to usage, implementation and enhancement. I decided to make Pickr event-driven.
Currently there are 4 events (see [Events](https://github.com/Simonwep/pickr/tree/event-driven#events) in the [event-driven-branch](https://github.com/Simonwep/pickr/tree/event-driven)) among `init` which was suggested in #64 by @st-spark.
See https://github.com/Simonwep/pickr/tree/event-driven#methods for how to use `on` and `off` :)

My idea is to fully drop all `onXYZ` support for the upcoming `0.4.0` version and replace these with event hooks.

Are there any more event-hooks, ideas, suggestions which can be implemented to simplify and improve the usage? Any ideas are welcome :)

**Comment by Simonwep** [comment]
Available since `0.4.0`

**Comment by st-spark** [comment]
It's seems that "useAsButton: true" kills event driven system `pickr.on('change', () => {});` dont work. If I set useAsButton: false, then all works fine

**Comment by st-spark** [comment]
And maybe 1 another feature. It'll be great if we could select where to put color on preview button (on what css attribute): color, background, background-color;

`const pickr = Pickr.create({
    el: '.color-picker',
    color_css_attr: 'background-color',
    ...
});`

**Comment by Simonwep** [comment]
1. To your first issue, yeah... seems like `appendToBody` and `showAlways` were broken :/
Fixed both in 85f08b8fa4767a7ddef91577756688000c9d1e6b and 9bf6c08515ad1a52a452167240dbba87c1010eb3. Tried to reproduce it [here](http://jsfiddle.net/sb35zofu/) - now everything (hopefully) works fine again.
2. What do you mean exactly? The button provided by pickr? Or your customized one usable with `useAsButton: true`?

**Comment by st-spark** [comment]
> @st-spark
> 
> 1. To your first issue, yeah... seems like `appendToBody` and `showAlways` were broken :/
>    Fixed both in [85f08b8](https://github.com/Simonwep/pickr/commit/85f08b8fa4767a7ddef91577756688000c9d1e6b) and [9bf6c08](https://github.com/Simonwep/pickr/commit/9bf6c08515ad1a52a452167240dbba87c1010eb3). Tried to reproduce it [here](http://jsfiddle.net/sb35zofu/) - now everything (hopefully) works fine again.
> 2. What do you mean exactly? The button provided by pickr? Or your customized one usable with `useAsButton: true`?

Thank you. Problem with `useAsButton: true` now fixed. It seems that problem was with  `appendToBody` and `showAlways` , anyway - thanks.
