### ISSUE TITLE
color parette not successfully initialized in showAlways mode

### ISSUE THREAD

**Issue by ohida** [Simonwep/pickr#67]
#### Do you want to request a **feature** or report a **bug**? 
bug

#### What is the current behavior?
Sometimes the color palatte and the color pointer is not successfully initialized in `showAlways` mode.
When I click the parette, it works fine (color parette is successfully updated).

![2019-02-21 16 21 36](https://user-images.githubusercontent.com/68521/53150828-d1d1f100-35f4-11e9-9da7-f0d7a5c733b6.png)

#### environment:
```
Pickr-version: 0.3.5
Browser-version:  Chrome 72.0.3626.109
Operating-system: macOS 10.14.3 
```

**Comment by Simonwep** [comment]
Duplicate of #59. Has been fixed here: 0fea09231951f00ab4e351236596ef7ab2a4ec44 (Apparently)
It's currently in no release, try the current master branch :)

**Comment by Simonwep** [comment]
Okay, published `0.3.6`. Should not also be available on npm :)

**Comment by ohida** [comment]
@Simonwep thank you so much.
updated to `0.3.6` via npm.

But still have the same problem...
![2019-02-21 22 47 23](https://user-images.githubusercontent.com/68521/53173319-c8637b80-362a-11e9-83ea-d6b3693daa6b.png)

I'm using Pickr in Vue Material's Tab component. I think this problem may be depends on my environment.
https://vuematerial.io/components/tabs

thank you for your help.

**Comment by Simonwep** [comment]
Tried to reproduce it here: https://codesandbox.io/s/yjvqyynjnx Maybe you could copy-paste the important parts of your code into codesandbox to show this issue :)

**Comment by ohida** [comment]
@Simonwep Thank you for the sample code. It works very fine in the tab.
I checked my code again, and found that another component causes the problem.
Sorry for the trouble.
Thank you for your great component and support.
