### ISSUE TITLE
save callback not called when Clear button is clicked

### ISSUE THREAD

**Issue by av01d** [Simonwep/pickr#68]
#### Do you want to request a **feature** or report a **bug**? 
**bug**

#### What is the current behavior?
When the clear button is clicked, only the `change` event is fired, not the `save` event.
I use pickr (inited with `components.interaction.clear = true`) to allow the users to *not* select a color, by clicking the Clear button. It's crucial to know when the user does this... I expect to get the `save` handler to be called.
The fix is very simple: 

```
    _clearColor() {
        ....
        // Fire listener
        this._emit('change',null);
        this._emit('save',null); // Add this
    }
```

#### Your environment:
```
Pickr-version (see Pickr.version): 0.4.0
Browser-version:  All
Operating-system:  All
```

**Comment by Simonwep** [comment]
Whoops, save should be called with `null`, not the change event. Fixed in 22aa5e64b210c8d7d284b37c7a6e03bdd8538594 :)

**Comment by sergeizhukov** [comment]
Btw when you click **clear**, on **save** event the _color_ argument is null

**Comment by Simonwep** [comment]
@sergeizhukov It has historical reasons and stays there for backwards compatibility (for now at least) :)

**Comment by sergeizhukov** [comment]
@Simonwep ah ok. I just click `clear` button and see something like `you can't invoke toHEXA() on null`. wat? I don't invoke toHEXA() on null. I don't have here's code at all. No I understand why.
