### ISSUE TITLE
Stop propagation ? (Collapse)

### ISSUE THREAD

**Issue by Nuranto** [Simonwep/pickr#7]
When adding pickr inside a bootstrap collapse, it would be great to have a stop propagation option to prevent the collapse.
Of course, that option could be used in a lot more cases.

**Comment by Simonwep** [comment]
I'm not sure if I want to add a extra option for this because it's in relation to another framework.
You could simple stop any propagation on the color picker like so:
```js
pickr.getRoot().root.addEventListener('click', e => e.stopImmediatePropagation());
```
`pickr.getRoot()` returns the component object and `.root` is the root component :)

**Comment by Simonwep** [comment]
Has the problem been solved for you? If yes I would close this issue.

**Comment by Nuranto** [comment]
I solved this with 

```
$(document).on('click', '[data-toggle=collapse] .prevent-toggle', function(e) {
       e.stopPropagation();
    });
```
and add a prevent-toggle class on pickr div...
I agree it's in relation to another framework, but actually you may have the issue with a lot of others framework!
Any way, you can close the issue, thanks for help ! (And thanks for Pickr :D)

**Comment by Simonwep** [comment]
Yeah, I see the problem. I will consider to add a `stopPropagation` option :)

**Comment by Simonwep** [comment]
Okay, I think I won't add such a option, it's (basically) special and solution from @Nuranto and mine works so far. If any more problem occurs regarding to it, feel free to re-open it! :)
