### ISSUE TITLE
Add / Remove swatches

### ISSUE THREAD

**Issue by darshithedpara** [Simonwep/pickr#70]
## Add / Remove new swatches after  pickr's initialization

* New flag required **Save to Swatche**
* On save color event if **Save to Swatche** is true then new color will be added into Swatche.
* If we want to add to remove single or multiple swatche programmatically then there should be a method called **updateSwatches**

**Comment by Simonwep** [comment]
I'm currently working on something like `addSwatch(String)` & `removeSwatch(String | Index)` :)
Will be, presumably, available in the next minor version.

**Comment by Simonwep** [comment]
A prototype has been added here 21c4af81257f2de43d47dd7d50bfeb391aa89673. See [Methods](https://github.com/Simonwep/pickr#methods) for usage :)

**Comment by Simonwep** [comment]
Available since `0.4.1`. See [Methods](https://github.com/Simonwep/pickr/tree/c9bc1f0d30a23ea0676b27bb968315e71cc57c70#methods)

**Comment by darshithedpara** [comment]
Hello  @Simonwep 
- New Color should be auto added to Swatche on save event is fire.
- There should be option to turn on/off auto save new colors to Swatche.

**Comment by Simonwep** [comment]
Such things are easier to implement by yourself. Why not use `addSwatch` in the save event? There's absolutely no need to add this to the core functionality.

**Comment by Simonwep** [comment]
@darshithedpara It's basically an one-liner:
```js
pickr.on('save', color => pickr.addSwatch(color.toRGBA()));
```
