### ISSUE TITLE
Pickr not working in safari 10.x

### ISSUE THREAD

**Issue by vinaypathak05** [Simonwep/pickr#71]
I have included 👍 <script src="https://cdn.jsdelivr.net/npm/pickr-widget/dist/pickr.min.js"></script> for Pickr plugin, its working good in other browsers but its not working in safari browser. please help me out.

**Comment by Simonwep** [comment]
Please provide a [JSFiddle](https://jsfiddle.net), what exactly is the problem? Which safari version? How is your setup? Which version? Did you make sure to load the css before js?

**Comment by vinaypathak05** [comment]
<div class="color-picker" ></div>

const pickr = new Pickr({
                el: '.color-picker',
                default: '#0000ff',
                components: {
                    preview: false,
                    opacity: false,
                    hue: true,
                    interaction: {
                        hex: true,
                        rgba: false,
                        hsva: false,
                        input: true,
                        clear: false,
                        save: true
                    }
                },

                // Button strings, brings the possibility to use a language other than English.
                strings: {
                    save: 'Save',  // Default for save button
                    clear: 'Clear' // Default for clear button
                },

                // User has changed the color
                onChange(hsva, instance) {
                    hsva;     // HSVa color object, if cleared null
                    instance; // Current Pickr instance
                },

                // User has clicked the save button
                onSave(hsva, instance) {
                    // same as onChange
                    var color = hsva.toHEX().toString();
                    $('#colorpicker').val(color);
                    $('.pdfBack').css({"background-color":color}); //Set PDF back cover color as choosen.
                }
            });

I'm using 10.1.2 safari version.

I have inculded:
css: <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pickr-widget/dist/pickr.min.css"/>
js: <script src="https://cdn.jsdelivr.net/npm/pickr-widget/dist/pickr.min.js"></script>

Yes i have added css before js.

**Comment by vinaypathak05** [comment]
Here is my jsfiddle:
https://jsfiddle.net/vinaykumar05/m6exsc4k/

**Comment by Simonwep** [comment]
Thank's, unfortunately I don't have access to a Mac, so if you could describe / paste the error massage I could try to fix it :)

**Comment by vinaypathak05** [comment]
![screen shot 2019-03-06 at 10 25 33 am](https://user-images.githubusercontent.com/48212201/53856954-5f044500-3ffa-11e9-8a8d-dce2513057d2.png)
![screen shot 2019-03-06 at 10 24 50 am](https://user-images.githubusercontent.com/48212201/53856956-5f044500-3ffa-11e9-85ad-77310b21fdfb.png)


Here is the error message i received and that position where pickr will display.

**Comment by Simonwep** [comment]
Well, Pickr is just something which is exposed. It's never used internally in Pickr. So the problem must be somewhere how you import it... Could you provide the code where you import Pickr (the css and js) an the Pickr instance is getting created?

**Comment by vinaypathak05** [comment]
Hello Simonwep, 
you can check : https://jsfiddle.net/vinaykumar05/m6exsc4k/
that working fine in other browsers. Only getting issue with Safari browser.

**Comment by Simonwep** [comment]
Also here,
1. Please use / update to the latest version before submitting an issue. You also used `pickr-widget` which is now deprecated, use `@simonwep/pickr` instead :)
2. Safari 10.x is not covered by [.browserlists](https://github.com/Simonwep/pickr/blob/master/.browserslistrc), so please use the es5 version which is provided to support older browsers. (Safari 10.x is not over the 1.5% most-used browsers limit)

See the updated fiddle which uses the latest version: https://jsfiddle.net/hg0uoL93/ (I've added the es5 build to the Ressources section of JSFiddle) :)

**Comment by vinaypathak05** [comment]
Hi Simonwep,

After using current version, my previous problem is solved, but now I'm not receiving color code form it in safari. Check this.

![screen shot 2019-03-07 at 11 59 31 am](https://user-images.githubusercontent.com/48212201/53936687-bffe4c80-40d0-11e9-9841-d95ccc125fcc.png)

**Comment by Simonwep** [comment]
Did you used the es5 version? I only can reproduce it in any way if I get enough informations to estamine what exactly the problem it. Moreover this version is as I said not covered by the current browser-targets and won't be because it only used by 0.3%. See [Can I Use - usage table](https://caniuse.com/usage-table)

**Comment by vinaypathak05** [comment]
Yes, I have used es5.
