### ISSUE TITLE
Cannot use `addSwatch`

### ISSUE THREAD

**Issue by hoaiduyit** [Simonwep/pickr#72]
#### Do you want to request a **feature** or report a **bug**? 
Bug

#### What is the current behavior?
I cannot use `addSwatch` from pickr API

#### Image
![capture1](https://user-images.githubusercontent.com/25114154/53792592-9fae8080-3f5e-11e9-9581-46ab1a3cd3f8.PNG)

#### Your environment:
ReactJS
```
Pickr-version (see Pickr.version): 0.4.0
NPM-version:  6.4.1
Operating-system:  Window OS
```

**Comment by Simonwep** [comment]
Please provide the steps how to reproduce it e.g. a JSFiddle :) Also please update your version before submitting a issue. Maybe it's already resolved.

**Comment by hoaiduyit** [comment]
I just updated to latest version and it's working now. Thank for a great library, bro.
