### ISSUE TITLE
pickr.destroyAndRemove() crashes due to typo in destroy method's name

### ISSUE THREAD

**Issue by tlaanemaa** [Simonwep/pickr#73]
`pickr.destroyAndRemove()` and `pickr.destroy()` both crash because they try to delete a `Selectable` component that has a typo in its `destroy` method.

The bug can be seen in pickr/src/js/helper/selectable.js at row 19
https://github.com/Simonwep/pickr/blob/master/src/js/helper/selectable.js#L19

The method is called `destory` instead of `destroy`

Thanks!

**Comment by Simonwep** [comment]
Oh damn, fixed in ad2bd78763853d0b0e521bd916c9a33a87b37f62 ... Sorry must have happened when I was refactoring the `selectable` module :/
