### ISSUE TITLE
Let the component "palette" be optional too

### ISSUE THREAD

**Issue by rastapopougros** [Simonwep/pickr#81]
Almost all components are optionals, but not the palette itself.

For some use cases, we need to let users choose colors ONLY from suggestions, so from swatches.

If the "palette" is also a component, with true or false, we will be able to have either
- only the palette
- or the palette and swatches
- or only swatches

And so Pickr will really takes in account all cases possible! :smiley: 

(I will try to look at the code, but I absolutely don't know webpack and all the thousand of tools needed, so I'm not sure I'm going to succeed. :smile: )

**Comment by Simonwep** [comment]
Hey, no problem :) But fantastic idea, will be added in the next days 😃

**Comment by rastapopougros** [comment]
Glad, thanks!

**Comment by Simonwep** [comment]
Added here: 8042007b53e82d7fc365f6c9d21cff767aa585cc
Because otherwise there would be enorm backward-compatibility issues `palette` will automatically set to `true` if either `preview`, `opacity` or `hue` are true. It wouldn't make sense to set preview to true without palette so yeah :)

**Comment by rastapopougros** [comment]
Thanks, it works very well and it's perfect!

(for the detail: for accessibility we apply the pickr either on an text input if the user can choose any value, or on a select list if values are limited. Pickr replace that first real field by a button if JS is here, and we save the value in a hidden. But if no JS, that's always ok, even if limited values.)
