### ISSUE TITLE
How to distinguish save and reset events?

### ISSUE THREAD

**Issue by AlbertRAR** [Simonwep/pickr#82]
Hello,
I'm a bit confused about this behavior. Save event is triggered by both "save" and "clear" buttons. 
How to trigger the action only by clear button?

**Comment by AlbertRAR** [comment]
I also noticed that init event triggers save and change events too. Is this a bug?

**Comment by Simonwep** [comment]
To your first point, yeah that's by purpose. `clear` is kinda a save event and triggers save with `null` as color. It's easier to use it IMO. See #68 and #5 :)

To the second one, would be yeah. But at least in `73.0.3683.103` `init` get's only called during ahem, init 😅  Or what do you mean exactly with "init event triggers save and change events too"?

**Comment by Simonwep** [comment]
I'll close it of inactivity. Feel free to re-open a new one if the issue persists :)
