### ISSUE TITLE
Breaking change

### ISSUE THREAD

**Issue by yzgw** [Simonwep/pickr#85]
`toHEX()` was renamed to `toHEXA()` at 0.4.10, and it breaks backward compatibility.

**Comment by Simonwep** [comment]
Function mapped here: 8b728a3ed1b4022d9d75113c1b9b487a2ac7fc65
Will be removed in 0.5.0, I'll publish 0.4.11 where `toHEX` will be available again.

**Comment by Pancake** [comment]
You should update the README too. Older sites using JSDelivr, which automatically updates, will unfortunately break because of this.

**Comment by Simonwep** [comment]
Oh, sure! Thanks for briefing me!
