### ISSUE TITLE
Initial Menu position makes menu potentially off-screen when button is on side of screen

### ISSUE THREAD

**Issue by rbonomo** [Simonwep/pickr#87]
If my '.color-picker' element is on the very right of the screen, the menu that is displayed is overflowed off-screen. Closing the menu then reopening fixes the position however.

![image](https://user-images.githubusercontent.com/5369553/57254318-d4de5a00-7005-11e9-9a3f-eddbb21bb3e8.png)

**Comment by Simonwep** [comment]
Got this kind of issue was opened way to often haha, I'm so sorry... fixed again. I'll soon release 1.0 which will be the first _stable_ release.

**Comment by rbonomo** [comment]
Thanks man :)
