### ISSUE TITLE
More positioning options

### ISSUE THREAD

**Issue by dotKev** [Simonwep/pickr#89]
#### Do you want to request a **feature** or report a **bug**? 
Bug

#### What is the current behavior?
Color picker should appear above the picker if `position: 'top'` is set.

#### If the current behavior is a bug, please provide the steps to reproduce and create a [JSFiddle](https://jsfiddle.net/).

See https://jsfiddle.net/dotkev/42cjnu0q/

Configure Pickr with `position: top` on a page with enough space for the picker to open above.

Notice that on the `div.pcr-app`, the only the `top` position is set. 
```html
<div class="pcr-app visible" style="top: 395.312px;">
...
</div>
```

#### What is the expected behavior?
I imagine that a `left` css style should be added to the `pcr-app` style attribute.

#### Your environment:
```
Pickr-version: 0.5.1
Used Pickr-bundle: normal
Browser-version: Version 74.0.3729.157 
Operating-system: MacOS 10.14.5 Beta (18F131a)  
```

**Comment by Simonwep** [comment]
Ugh, this is actually a typo in the README: `[...] top, left and middle relativ to the picker button. [...]` instead of top there should be right. Is fixed :)

Pickr will automatically decide if it should be on top or bottom, determined if it's clipped 😄

**Comment by dotKev** [comment]
For my specific needs, `top` would certainly be nice, but `right` actually works in this instance. Perhaps the `padding` at https://github.com/Simonwep/pickr/blob/master/src/js/pickr.js#L377 could be configurable for edge detection, such as a [top, right, bottom, left] buffer *or* an optional edge-detection dom element that defaults to `window`? 

I have some page structure that gets in the way and clips the color picker (`overflow: hidden`) because all edge detection is based on the window and not a containing element.

Just ideas. I love that you've created a light-weight color picker. All the others I've tried are terrible. Also, I'd love to assist with the feature I just mentioned, but I just don't have the availability at the moment. Thanks again!

**Comment by Simonwep** [comment]
You're welcome :blush:
An enhanced position control sounds great! I'll take a look at it :)

**Comment by Simonwep** [comment]
It's currently in progress at the [enhanced-positioning](https://github.com/Simonwep/pickr/tree/enhanced-positioning) branch.
