### ISSUE TITLE
v0.6.0 is broken

### ISSUE THREAD

**Issue by LuukvE** [Simonwep/pickr#90]
#### Do you want to request a **feature** or report a **bug**? 
Bug. Seems to be related to `nanopop.js`.
`nanopop.js:44 Uncaught TypeError: t is not iterable at p (nanopop.js:44)`

#### What is the current behavior?
No `save` or `init` events and left positition not set on color pick panel.

#### If the current behavior is a bug, please provide the steps to reproduce and create a [JSFiddle](https://jsfiddle.net/).
JS error in console on initialisation. No steps needed.

#### What is the expected behavior?
No crash.

#### Your environment:
```
Pickr-version (see Pickr.version): 0.6.0
Used Pickr-bundle (es5 or normal one): ` /npm/@simonwep/pickr@0.6.0/dist/pickr.min.js`
Browser-version:  Chrome 74
Operating-system:  Windows 10
```

**Comment by Simonwep** [comment]
How does your configuration object look like? There are breaking changes between 0.5 and 0.6 :)
