### ISSUE TITLE
Some extra stuff in dist/pickr.min.css 

### ISSUE THREAD

**Issue by dotKev** [Simonwep/pickr#91]
#### Do you want to request a **feature** or report a **bug**? 
BUG
#### What is the current behavior?
The `0.6.1` version of `dist/pickr.min.css` appears to have some unintended junk in the sourceMappingURL that is tripping up my linting/purgecss.
```CSS
/*# sourceMappingURL=pickr.min.js.map*/ap*/
```
When I build it myself, the line is
```CSS
/*# sourceMappingURL=pickr.es5.min.js.map*/
```

#### What is the expected behavior?
Cleaned up output. Just a repackaging should take care of it. :-) 

#### Your environment:
```
Pickr-version (see Pickr.version): 0.6.1
```

**Comment by Simonwep** [comment]
Huh, that's strange :suspect: Thank's for the PR! I'll take a look at it.
