### ISSUE TITLE
Disabling opacity component causes issues with swatches

### ISSUE THREAD

**Issue by kkeith-adg** [Simonwep/pickr#93]
#### Do you want to request a **feature** or report a **bug**? 
Bug

#### What is the current behavior?
Disabling opacity component causes swatches to no longer work properly. It seems to select the incorrect swatch and only gets the correct one on the second selection. Happens consistently in my software, fiddle seems intermittent.

[https://jsfiddle.net/e7o98g3c/](https://jsfiddle.net/e7o98g3c/)

#### What is the expected behavior?
Swatch selection choses proper color upon click.

#### Your environment:
```
Pickr-version (see Pickr.version): 0.6.1
Used Pickr-bundle (es5 or normal one): normal
Browser-version: Firefox 67
Operating-system: MacOS Mojave
```

**Comment by Simonwep** [comment]
Fixed in fe0264ed92091ba6b03d3947975851b4955e2a60 :)
