### ISSUE TITLE
Maintain a changelog

### ISSUE THREAD

**Issue by astronomersiva** [Simonwep/pickr#94]
It would be great if there was a changelog that's being maintained so that people who use pickr can know what the breaking changes are between versions. Right now, looking at the commits is the only way and it can get tiring at times.

**Comment by Simonwep** [comment]
Great idea, I'll do if for now on - and edit the releases of `0.5.0` up to `0.6.2`!

**Comment by astronomersiva** [comment]
Thanks @Simonwep! It would be better if you indicate the breaking changes in the releases page. It's still not clear as to what was the breaking change between 0.5 and 0.6.

**Comment by Simonwep** [comment]
To be honest, I'm not that sure what the problem was. Could be something related to the now available positioning options: `left` is now `start` and right `end` :suspect:
