### ISSUE TITLE
Bug: Alpha value in HEX is shown in decimal

### ISSUE THREAD

**Issue by davidglezz** [Simonwep/pickr#95]
![image](https://user-images.githubusercontent.com/194784/58754008-9767d200-84c8-11e9-9190-e8edc7a84e96.png)

Windows 10, Chrome 74

**Comment by Simonwep** [comment]
Oh, seems like some parameter got really messed up. Thanks! Fixed in cc84efc68f440bde87f77c4ad458a3382c23d6d3
