### ISSUE TITLE
0.6.3 pickr.min.css garbled again

### ISSUE THREAD

**Issue by dotKev** [Simonwep/pickr#96]
#### Do you want to request a **feature** or report a **bug**? 
Bug 

#### What is the current behavior?
Garbled sourcemap url string in https://github.com/Simonwep/pickr/blob/0.6.3/dist/pickr.min.css#L3

0.6.3 dist/pickr.min.css has this garbled line again
```css
/*# sourceMappingURL=pickr.min.js.map*/ap*/
```
which breaks when trying to include the file in my project. If I build 0.6.3 myself, it outputs correctly. I'm currently just locking down to version `0.6.2`.

**Comment by Simonwep** [comment]
I'm really confused, every time I rebuild the first time this get's messed up... I've updated the dependencies, seems like It's now correct - I'll keep that problem in mind!

**Comment by dotKev** [comment]
Yeah, I can't figure it out yet either. I played with the build settings, and thought I solved it, but reverted my changes as a sanity check and couldn't recreate the initial error. 🤷‍♂

**Comment by Simonwep** [comment]
I'll close it, many thanks to @pjfreeze for solving this issue :)

**Comment by Simonwep** [comment]
I've published `0.6.4` where _finally_ this is fixed :)
